/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.AttachmentRequestPayload;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Вложение при отправке сообщения. Тип определяет, какие поля payload или координаты должны быть заполнены.  Источник описания: [NewMessageBody](https://dev.max.ru/docs-api/objects/NewMessageBody)
 */
@JsonPropertyOrder({
  AttachmentRequest.JSON_PROPERTY_TYPE,
  AttachmentRequest.JSON_PROPERTY_PAYLOAD,
  AttachmentRequest.JSON_PROPERTY_LATITUDE,
  AttachmentRequest.JSON_PROPERTY_LONGITUDE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class AttachmentRequest {
  /**
   * Тип вложения
   */
  public enum TypeEnum {
    IMAGE(String.valueOf("image")),
    
    VIDEO(String.valueOf("video")),
    
    AUDIO(String.valueOf("audio")),
    
    FILE(String.valueOf("file")),
    
    STICKER(String.valueOf("sticker")),
    
    CONTACT(String.valueOf("contact")),
    
    INLINE_KEYBOARD(String.valueOf("inline_keyboard")),
    
    SHARE(String.valueOf("share")),
    
    LOCATION(String.valueOf("location"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_PAYLOAD = "payload";
  @jakarta.annotation.Nullable
  private AttachmentRequestPayload payload;

  public static final String JSON_PROPERTY_LATITUDE = "latitude";
  @jakarta.annotation.Nullable
  private JsonNullable<BigDecimal> latitude = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_LONGITUDE = "longitude";
  @jakarta.annotation.Nullable
  private JsonNullable<BigDecimal> longitude = JsonNullable.<BigDecimal>undefined();

  public AttachmentRequest() {
  }

  public AttachmentRequest type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Тип вложения
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public AttachmentRequest payload(@jakarta.annotation.Nullable AttachmentRequestPayload payload) {
    
    this.payload = payload;
    return this;
  }

  /**
   * Get payload
   * @return payload
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYLOAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AttachmentRequestPayload getPayload() {
    return payload;
  }


  @JsonProperty(JSON_PROPERTY_PAYLOAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayload(@jakarta.annotation.Nullable AttachmentRequestPayload payload) {
    this.payload = payload;
  }

  public AttachmentRequest latitude(@jakarta.annotation.Nullable BigDecimal latitude) {
    this.latitude = JsonNullable.<BigDecimal>of(latitude);
    
    return this;
  }

  /**
   * Широта Обязательно, когда type&#x3D;location.
   * @return latitude
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getLatitude() {
        return latitude.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getLatitude_JsonNullable() {
    return latitude;
  }
  
  @JsonProperty(JSON_PROPERTY_LATITUDE)
  public void setLatitude_JsonNullable(JsonNullable<BigDecimal> latitude) {
    this.latitude = latitude;
  }

  public void setLatitude(@jakarta.annotation.Nullable BigDecimal latitude) {
    this.latitude = JsonNullable.<BigDecimal>of(latitude);
  }

  public AttachmentRequest longitude(@jakarta.annotation.Nullable BigDecimal longitude) {
    this.longitude = JsonNullable.<BigDecimal>of(longitude);
    
    return this;
  }

  /**
   * Долгота Обязательно, когда type&#x3D;location.
   * @return longitude
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getLongitude() {
        return longitude.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getLongitude_JsonNullable() {
    return longitude;
  }
  
  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  public void setLongitude_JsonNullable(JsonNullable<BigDecimal> longitude) {
    this.longitude = longitude;
  }

  public void setLongitude(@jakarta.annotation.Nullable BigDecimal longitude) {
    this.longitude = JsonNullable.<BigDecimal>of(longitude);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttachmentRequest attachmentRequest = (AttachmentRequest) o;
    return Objects.equals(this.type, attachmentRequest.type) &&
        Objects.equals(this.payload, attachmentRequest.payload) &&
        equalsNullable(this.latitude, attachmentRequest.latitude) &&
        equalsNullable(this.longitude, attachmentRequest.longitude);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, payload, hashCodeNullable(latitude), hashCodeNullable(longitude));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentRequest {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

