/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.AttachmentPayload;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Вложение сообщения. Тип определяет, какие поля payload и дополнительные атрибуты обычно присутствуют.  Источник описания: [Message](https://dev.max.ru/docs-api/objects/Message)
 */
@JsonPropertyOrder({
  Attachment.JSON_PROPERTY_TYPE,
  Attachment.JSON_PROPERTY_PAYLOAD,
  Attachment.JSON_PROPERTY_FILENAME,
  Attachment.JSON_PROPERTY_SIZE,
  Attachment.JSON_PROPERTY_WIDTH,
  Attachment.JSON_PROPERTY_HEIGHT,
  Attachment.JSON_PROPERTY_DURATION,
  Attachment.JSON_PROPERTY_THUMBNAIL,
  Attachment.JSON_PROPERTY_TITLE,
  Attachment.JSON_PROPERTY_DESCRIPTION,
  Attachment.JSON_PROPERTY_IMAGE_URL,
  Attachment.JSON_PROPERTY_LATITUDE,
  Attachment.JSON_PROPERTY_LONGITUDE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class Attachment {
  /**
   * Тип вложения
   */
  public enum TypeEnum {
    IMAGE(String.valueOf("image")),
    
    VIDEO(String.valueOf("video")),
    
    AUDIO(String.valueOf("audio")),
    
    FILE(String.valueOf("file")),
    
    STICKER(String.valueOf("sticker")),
    
    CONTACT(String.valueOf("contact")),
    
    INLINE_KEYBOARD(String.valueOf("inline_keyboard")),
    
    SHARE(String.valueOf("share")),
    
    LOCATION(String.valueOf("location"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_PAYLOAD = "payload";
  @jakarta.annotation.Nullable
  private AttachmentPayload payload;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  @jakarta.annotation.Nullable
  private JsonNullable<String> filename = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SIZE = "size";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> size = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_WIDTH = "width";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> width = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_HEIGHT = "height";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> height = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> duration = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_THUMBNAIL = "thumbnail";
  @jakarta.annotation.Nullable
  private JsonNullable<String> thumbnail = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TITLE = "title";
  @jakarta.annotation.Nullable
  private JsonNullable<String> title = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IMAGE_URL = "image_url";
  @jakarta.annotation.Nullable
  private JsonNullable<String> imageUrl = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LATITUDE = "latitude";
  @jakarta.annotation.Nullable
  private JsonNullable<BigDecimal> latitude = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_LONGITUDE = "longitude";
  @jakarta.annotation.Nullable
  private JsonNullable<BigDecimal> longitude = JsonNullable.<BigDecimal>undefined();

  public Attachment() {
  }

  public Attachment type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Тип вложения
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public Attachment payload(@jakarta.annotation.Nullable AttachmentPayload payload) {
    
    this.payload = payload;
    return this;
  }

  /**
   * Get payload
   * @return payload
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYLOAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AttachmentPayload getPayload() {
    return payload;
  }


  @JsonProperty(JSON_PROPERTY_PAYLOAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayload(@jakarta.annotation.Nullable AttachmentPayload payload) {
    this.payload = payload;
  }

  public Attachment filename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
    
    return this;
  }

  /**
   * Имя файла Обязательно, когда type&#x3D;file.
   * @return filename
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getFilename() {
        return filename.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FILENAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFilename_JsonNullable() {
    return filename;
  }
  
  @JsonProperty(JSON_PROPERTY_FILENAME)
  public void setFilename_JsonNullable(JsonNullable<String> filename) {
    this.filename = filename;
  }

  public void setFilename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
  }

  public Attachment size(@jakarta.annotation.Nullable Integer size) {
    this.size = JsonNullable.<Integer>of(size);
    
    return this;
  }

  /**
   * Размер файла Обязательно, когда type&#x3D;file.
   * @return size
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getSize() {
        return size.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getSize_JsonNullable() {
    return size;
  }
  
  @JsonProperty(JSON_PROPERTY_SIZE)
  public void setSize_JsonNullable(JsonNullable<Integer> size) {
    this.size = size;
  }

  public void setSize(@jakarta.annotation.Nullable Integer size) {
    this.size = JsonNullable.<Integer>of(size);
  }

  public Attachment width(@jakarta.annotation.Nullable Integer width) {
    this.width = JsonNullable.<Integer>of(width);
    
    return this;
  }

  /**
   * Ширина медиа Обязательно, когда type in {image, video}.
   * @return width
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getWidth() {
        return width.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getWidth_JsonNullable() {
    return width;
  }
  
  @JsonProperty(JSON_PROPERTY_WIDTH)
  public void setWidth_JsonNullable(JsonNullable<Integer> width) {
    this.width = width;
  }

  public void setWidth(@jakarta.annotation.Nullable Integer width) {
    this.width = JsonNullable.<Integer>of(width);
  }

  public Attachment height(@jakarta.annotation.Nullable Integer height) {
    this.height = JsonNullable.<Integer>of(height);
    
    return this;
  }

  /**
   * Высота медиа Обязательно, когда type in {image, video}.
   * @return height
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getHeight() {
        return height.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getHeight_JsonNullable() {
    return height;
  }
  
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  public void setHeight_JsonNullable(JsonNullable<Integer> height) {
    this.height = height;
  }

  public void setHeight(@jakarta.annotation.Nullable Integer height) {
    this.height = JsonNullable.<Integer>of(height);
  }

  public Attachment duration(@jakarta.annotation.Nullable Integer duration) {
    this.duration = JsonNullable.<Integer>of(duration);
    
    return this;
  }

  /**
   * Длительность медиа в секундах Обязательно, когда type in {video, audio}.
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getDuration() {
        return duration.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getDuration_JsonNullable() {
    return duration;
  }
  
  @JsonProperty(JSON_PROPERTY_DURATION)
  public void setDuration_JsonNullable(JsonNullable<Integer> duration) {
    this.duration = duration;
  }

  public void setDuration(@jakarta.annotation.Nullable Integer duration) {
    this.duration = JsonNullable.<Integer>of(duration);
  }

  public Attachment thumbnail(@jakarta.annotation.Nullable String thumbnail) {
    this.thumbnail = JsonNullable.<String>of(thumbnail);
    
    return this;
  }

  /**
   * Миниатюра видео Обязательно, когда type&#x3D;video.
   * @return thumbnail
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getThumbnail() {
        return thumbnail.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_THUMBNAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getThumbnail_JsonNullable() {
    return thumbnail;
  }
  
  @JsonProperty(JSON_PROPERTY_THUMBNAIL)
  public void setThumbnail_JsonNullable(JsonNullable<String> thumbnail) {
    this.thumbnail = thumbnail;
  }

  public void setThumbnail(@jakarta.annotation.Nullable String thumbnail) {
    this.thumbnail = JsonNullable.<String>of(thumbnail);
  }

  public Attachment title(@jakarta.annotation.Nullable String title) {
    this.title = JsonNullable.<String>of(title);
    
    return this;
  }

  /**
   * Заголовок вложения Обязательно, когда type&#x3D;share.
   * @return title
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getTitle() {
        return title.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTitle_JsonNullable() {
    return title;
  }
  
  @JsonProperty(JSON_PROPERTY_TITLE)
  public void setTitle_JsonNullable(JsonNullable<String> title) {
    this.title = title;
  }

  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = JsonNullable.<String>of(title);
  }

  public Attachment description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * Описание вложения Обязательно, когда type&#x3D;share.
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  public Attachment imageUrl(@jakarta.annotation.Nullable String imageUrl) {
    this.imageUrl = JsonNullable.<String>of(imageUrl);
    
    return this;
  }

  /**
   * URL изображения для share-вложения Обязательно, когда type&#x3D;share.
   * @return imageUrl
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getImageUrl() {
        return imageUrl.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IMAGE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getImageUrl_JsonNullable() {
    return imageUrl;
  }
  
  @JsonProperty(JSON_PROPERTY_IMAGE_URL)
  public void setImageUrl_JsonNullable(JsonNullable<String> imageUrl) {
    this.imageUrl = imageUrl;
  }

  public void setImageUrl(@jakarta.annotation.Nullable String imageUrl) {
    this.imageUrl = JsonNullable.<String>of(imageUrl);
  }

  public Attachment latitude(@jakarta.annotation.Nullable BigDecimal latitude) {
    this.latitude = JsonNullable.<BigDecimal>of(latitude);
    
    return this;
  }

  /**
   * Широта Обязательно, когда type&#x3D;location.
   * @return latitude
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getLatitude() {
        return latitude.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getLatitude_JsonNullable() {
    return latitude;
  }
  
  @JsonProperty(JSON_PROPERTY_LATITUDE)
  public void setLatitude_JsonNullable(JsonNullable<BigDecimal> latitude) {
    this.latitude = latitude;
  }

  public void setLatitude(@jakarta.annotation.Nullable BigDecimal latitude) {
    this.latitude = JsonNullable.<BigDecimal>of(latitude);
  }

  public Attachment longitude(@jakarta.annotation.Nullable BigDecimal longitude) {
    this.longitude = JsonNullable.<BigDecimal>of(longitude);
    
    return this;
  }

  /**
   * Долгота Обязательно, когда type&#x3D;location.
   * @return longitude
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getLongitude() {
        return longitude.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getLongitude_JsonNullable() {
    return longitude;
  }
  
  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  public void setLongitude_JsonNullable(JsonNullable<BigDecimal> longitude) {
    this.longitude = longitude;
  }

  public void setLongitude(@jakarta.annotation.Nullable BigDecimal longitude) {
    this.longitude = JsonNullable.<BigDecimal>of(longitude);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Attachment attachment = (Attachment) o;
    return Objects.equals(this.type, attachment.type) &&
        Objects.equals(this.payload, attachment.payload) &&
        equalsNullable(this.filename, attachment.filename) &&
        equalsNullable(this.size, attachment.size) &&
        equalsNullable(this.width, attachment.width) &&
        equalsNullable(this.height, attachment.height) &&
        equalsNullable(this.duration, attachment.duration) &&
        equalsNullable(this.thumbnail, attachment.thumbnail) &&
        equalsNullable(this.title, attachment.title) &&
        equalsNullable(this.description, attachment.description) &&
        equalsNullable(this.imageUrl, attachment.imageUrl) &&
        equalsNullable(this.latitude, attachment.latitude) &&
        equalsNullable(this.longitude, attachment.longitude);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, payload, hashCodeNullable(filename), hashCodeNullable(size), hashCodeNullable(width), hashCodeNullable(height), hashCodeNullable(duration), hashCodeNullable(thumbnail), hashCodeNullable(title), hashCodeNullable(description), hashCodeNullable(imageUrl), hashCodeNullable(latitude), hashCodeNullable(longitude));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Attachment {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

