/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Объединённая best-effort схема payload для Attachment. Поля объединены по всем типам вложений, которые переключаются в UI документации.  Источник описания: [Message](https://dev.max.ru/docs-api/objects/Message)
 */
@JsonPropertyOrder({
  AttachmentPayload.JSON_PROPERTY_PHOTO_ID,
  AttachmentPayload.JSON_PROPERTY_TOKEN,
  AttachmentPayload.JSON_PROPERTY_URL,
  AttachmentPayload.JSON_PROPERTY_FILENAME,
  AttachmentPayload.JSON_PROPERTY_SIZE,
  AttachmentPayload.JSON_PROPERTY_CODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class AttachmentPayload {
  public static final String JSON_PROPERTY_PHOTO_ID = "photo_id";
  @jakarta.annotation.Nullable
  private JsonNullable<Long> photoId = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_TOKEN = "token";
  @jakarta.annotation.Nullable
  private JsonNullable<String> token = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private JsonNullable<String> url = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FILENAME = "filename";
  @jakarta.annotation.Nullable
  private JsonNullable<String> filename = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SIZE = "size";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> size = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nullable
  private JsonNullable<String> code = JsonNullable.<String>undefined();

  public AttachmentPayload() {
  }

  public AttachmentPayload photoId(@jakarta.annotation.Nullable Long photoId) {
    this.photoId = JsonNullable.<Long>of(photoId);
    
    return this;
  }

  /**
   * Уникальный ID изображения Обязательно, когда type&#x3D;image.
   * @return photoId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getPhotoId() {
        return photoId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PHOTO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getPhotoId_JsonNullable() {
    return photoId;
  }
  
  @JsonProperty(JSON_PROPERTY_PHOTO_ID)
  public void setPhotoId_JsonNullable(JsonNullable<Long> photoId) {
    this.photoId = photoId;
  }

  public void setPhotoId(@jakarta.annotation.Nullable Long photoId) {
    this.photoId = JsonNullable.<Long>of(photoId);
  }

  public AttachmentPayload token(@jakarta.annotation.Nullable String token) {
    this.token = JsonNullable.<String>of(token);
    
    return this;
  }

  /**
   * Токен вложения Используется, когда type in {image, video, audio, file} при наличии серверного media token.
   * @return token
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getToken() {
        return token.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getToken_JsonNullable() {
    return token;
  }
  
  @JsonProperty(JSON_PROPERTY_TOKEN)
  public void setToken_JsonNullable(JsonNullable<String> token) {
    this.token = token;
  }

  public void setToken(@jakarta.annotation.Nullable String token) {
    this.token = JsonNullable.<String>of(token);
  }

  public AttachmentPayload url(@jakarta.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
    
    return this;
  }

  /**
   * URL изображения или медиафайла Обязательно, когда type&#x3D;image.
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getUrl() {
        return url.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUrl_JsonNullable() {
    return url;
  }
  
  @JsonProperty(JSON_PROPERTY_URL)
  public void setUrl_JsonNullable(JsonNullable<String> url) {
    this.url = url;
  }

  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
  }

  public AttachmentPayload filename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
    
    return this;
  }

  /**
   * Имя файла Обязательно, когда type&#x3D;file.
   * @return filename
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getFilename() {
        return filename.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FILENAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFilename_JsonNullable() {
    return filename;
  }
  
  @JsonProperty(JSON_PROPERTY_FILENAME)
  public void setFilename_JsonNullable(JsonNullable<String> filename) {
    this.filename = filename;
  }

  public void setFilename(@jakarta.annotation.Nullable String filename) {
    this.filename = JsonNullable.<String>of(filename);
  }

  public AttachmentPayload size(@jakarta.annotation.Nullable Integer size) {
    this.size = JsonNullable.<Integer>of(size);
    
    return this;
  }

  /**
   * Размер файла Обязательно, когда type&#x3D;file.
   * @return size
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getSize() {
        return size.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getSize_JsonNullable() {
    return size;
  }
  
  @JsonProperty(JSON_PROPERTY_SIZE)
  public void setSize_JsonNullable(JsonNullable<Integer> size) {
    this.size = size;
  }

  public void setSize(@jakarta.annotation.Nullable Integer size) {
    this.size = JsonNullable.<Integer>of(size);
  }

  public AttachmentPayload code(@jakarta.annotation.Nullable String code) {
    this.code = JsonNullable.<String>of(code);
    
    return this;
  }

  /**
   * Код стикера Обязательно, когда type&#x3D;sticker.
   * @return code
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getCode() {
        return code.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCode_JsonNullable() {
    return code;
  }
  
  @JsonProperty(JSON_PROPERTY_CODE)
  public void setCode_JsonNullable(JsonNullable<String> code) {
    this.code = code;
  }

  public void setCode(@jakarta.annotation.Nullable String code) {
    this.code = JsonNullable.<String>of(code);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttachmentPayload attachmentPayload = (AttachmentPayload) o;
    return equalsNullable(this.photoId, attachmentPayload.photoId) &&
        equalsNullable(this.token, attachmentPayload.token) &&
        equalsNullable(this.url, attachmentPayload.url) &&
        equalsNullable(this.filename, attachmentPayload.filename) &&
        equalsNullable(this.size, attachmentPayload.size) &&
        equalsNullable(this.code, attachmentPayload.code);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(photoId), hashCodeNullable(token), hashCodeNullable(url), hashCodeNullable(filename), hashCodeNullable(size), hashCodeNullable(code));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentPayload {\n");
    sb.append("    photoId: ").append(toIndentedString(photoId)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

