/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Объединённая best-effort схема payload для AttachmentRequest. Поля объединены по всем типам вложений, которые переключаются в UI документации.  Источник описания: [NewMessageBody](https://dev.max.ru/docs-api/objects/NewMessageBody)
 */
@JsonPropertyOrder({
  AttachmentRequestPayload.JSON_PROPERTY_TOKEN,
  AttachmentRequestPayload.JSON_PROPERTY_URL,
  AttachmentRequestPayload.JSON_PROPERTY_PHOTOS,
  AttachmentRequestPayload.JSON_PROPERTY_NAME,
  AttachmentRequestPayload.JSON_PROPERTY_CONTACT_ID,
  AttachmentRequestPayload.JSON_PROPERTY_VCF_INFO,
  AttachmentRequestPayload.JSON_PROPERTY_VCF_PHONE,
  AttachmentRequestPayload.JSON_PROPERTY_CODE,
  AttachmentRequestPayload.JSON_PROPERTY_BUTTONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class AttachmentRequestPayload {
  public static final String JSON_PROPERTY_TOKEN = "token";
  @jakarta.annotation.Nullable
  private JsonNullable<String> token = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private JsonNullable<String> url = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PHOTOS = "photos";
  @jakarta.annotation.Nullable
  private JsonNullable<Object> photos = JsonNullable.<Object>undefined();

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CONTACT_ID = "contact_id";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> contactId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_VCF_INFO = "vcf_info";
  @jakarta.annotation.Nullable
  private JsonNullable<String> vcfInfo = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VCF_PHONE = "vcf_phone";
  @jakarta.annotation.Nullable
  private JsonNullable<String> vcfPhone = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nullable
  private JsonNullable<String> code = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BUTTONS = "buttons";
  @jakarta.annotation.Nullable
  private JsonNullable<List<List<Object>>> buttons = JsonNullable.<List<List<Object>>>undefined();

  public AttachmentRequestPayload() {
  }

  public AttachmentRequestPayload token(@jakarta.annotation.Nullable String token) {
    this.token = JsonNullable.<String>of(token);
    
    return this;
  }

  /**
   * Токен загруженного медиафайла Обязательно, когда type in {video, audio, file}; type&#x3D;image при отправке изображения через upload token.
   * @return token
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getToken() {
        return token.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getToken_JsonNullable() {
    return token;
  }
  
  @JsonProperty(JSON_PROPERTY_TOKEN)
  public void setToken_JsonNullable(JsonNullable<String> token) {
    this.token = token;
  }

  public void setToken(@jakarta.annotation.Nullable String token) {
    this.token = JsonNullable.<String>of(token);
  }

  public AttachmentRequestPayload url(@jakarta.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
    
    return this;
  }

  /**
   * URL изображения Обязательно, когда type&#x3D;image при отправке изображения по URL.
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getUrl() {
        return url.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUrl_JsonNullable() {
    return url;
  }
  
  @JsonProperty(JSON_PROPERTY_URL)
  public void setUrl_JsonNullable(JsonNullable<String> url) {
    this.url = url;
  }

  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
  }

  public AttachmentRequestPayload photos(@jakarta.annotation.Nullable Object photos) {
    this.photos = JsonNullable.<Object>of(photos);
    
    return this;
  }

  /**
   * Набор вариантов изображения по ключам Обязательно, когда type&#x3D;image при отправке изображения набором вариантов.
   * @return photos
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getPhotos() {
        return photos.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PHOTOS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getPhotos_JsonNullable() {
    return photos;
  }
  
  @JsonProperty(JSON_PROPERTY_PHOTOS)
  public void setPhotos_JsonNullable(JsonNullable<Object> photos) {
    this.photos = photos;
  }

  public void setPhotos(@jakarta.annotation.Nullable Object photos) {
    this.photos = JsonNullable.<Object>of(photos);
  }

  public AttachmentRequestPayload name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    
    return this;
  }

  /**
   * Имя контакта Обязательно, когда type&#x3D;contact при передаче карточки контакта в явном виде.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }

  public AttachmentRequestPayload contactId(@jakarta.annotation.Nullable Integer contactId) {
    this.contactId = JsonNullable.<Integer>of(contactId);
    
    return this;
  }

  /**
   * ID контакта Обязательно, когда type&#x3D;contact при передаче контакта по идентификатору.
   * @return contactId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getContactId() {
        return contactId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONTACT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getContactId_JsonNullable() {
    return contactId;
  }
  
  @JsonProperty(JSON_PROPERTY_CONTACT_ID)
  public void setContactId_JsonNullable(JsonNullable<Integer> contactId) {
    this.contactId = contactId;
  }

  public void setContactId(@jakarta.annotation.Nullable Integer contactId) {
    this.contactId = JsonNullable.<Integer>of(contactId);
  }

  public AttachmentRequestPayload vcfInfo(@jakarta.annotation.Nullable String vcfInfo) {
    this.vcfInfo = JsonNullable.<String>of(vcfInfo);
    
    return this;
  }

  /**
   * VCF-данные контакта Обязательно, когда type&#x3D;contact при передаче контакта как vCard.
   * @return vcfInfo
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getVcfInfo() {
        return vcfInfo.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VCF_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getVcfInfo_JsonNullable() {
    return vcfInfo;
  }
  
  @JsonProperty(JSON_PROPERTY_VCF_INFO)
  public void setVcfInfo_JsonNullable(JsonNullable<String> vcfInfo) {
    this.vcfInfo = vcfInfo;
  }

  public void setVcfInfo(@jakarta.annotation.Nullable String vcfInfo) {
    this.vcfInfo = JsonNullable.<String>of(vcfInfo);
  }

  public AttachmentRequestPayload vcfPhone(@jakarta.annotation.Nullable String vcfPhone) {
    this.vcfPhone = JsonNullable.<String>of(vcfPhone);
    
    return this;
  }

  /**
   * Телефон контакта Обязательно, когда type&#x3D;contact при передаче контакта как vCard/телефонной карточки.
   * @return vcfPhone
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getVcfPhone() {
        return vcfPhone.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VCF_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getVcfPhone_JsonNullable() {
    return vcfPhone;
  }
  
  @JsonProperty(JSON_PROPERTY_VCF_PHONE)
  public void setVcfPhone_JsonNullable(JsonNullable<String> vcfPhone) {
    this.vcfPhone = vcfPhone;
  }

  public void setVcfPhone(@jakarta.annotation.Nullable String vcfPhone) {
    this.vcfPhone = JsonNullable.<String>of(vcfPhone);
  }

  public AttachmentRequestPayload code(@jakarta.annotation.Nullable String code) {
    this.code = JsonNullable.<String>of(code);
    
    return this;
  }

  /**
   * Код стикера Обязательно, когда type&#x3D;sticker.
   * @return code
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getCode() {
        return code.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCode_JsonNullable() {
    return code;
  }
  
  @JsonProperty(JSON_PROPERTY_CODE)
  public void setCode_JsonNullable(JsonNullable<String> code) {
    this.code = code;
  }

  public void setCode(@jakarta.annotation.Nullable String code) {
    this.code = JsonNullable.<String>of(code);
  }

  public AttachmentRequestPayload buttons(@jakarta.annotation.Nullable List<List<Object>> buttons) {
    this.buttons = JsonNullable.<List<List<Object>>>of(buttons);
    
    return this;
  }

  public AttachmentRequestPayload addButtonsItem(List<Object> buttonsItem) {
    if (this.buttons == null || !this.buttons.isPresent()) {
      this.buttons = JsonNullable.<List<List<Object>>>of(new ArrayList<>());
    }
    try {
      this.buttons.get().add(buttonsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Кнопки inline-клавиатуры Обязательно, когда type&#x3D;inline_keyboard.
   * @return buttons
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<List<Object>> getButtons() {
        return buttons.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BUTTONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<List<Object>>> getButtons_JsonNullable() {
    return buttons;
  }
  
  @JsonProperty(JSON_PROPERTY_BUTTONS)
  public void setButtons_JsonNullable(JsonNullable<List<List<Object>>> buttons) {
    this.buttons = buttons;
  }

  public void setButtons(@jakarta.annotation.Nullable List<List<Object>> buttons) {
    this.buttons = JsonNullable.<List<List<Object>>>of(buttons);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttachmentRequestPayload attachmentRequestPayload = (AttachmentRequestPayload) o;
    return equalsNullable(this.token, attachmentRequestPayload.token) &&
        equalsNullable(this.url, attachmentRequestPayload.url) &&
        equalsNullable(this.photos, attachmentRequestPayload.photos) &&
        equalsNullable(this.name, attachmentRequestPayload.name) &&
        equalsNullable(this.contactId, attachmentRequestPayload.contactId) &&
        equalsNullable(this.vcfInfo, attachmentRequestPayload.vcfInfo) &&
        equalsNullable(this.vcfPhone, attachmentRequestPayload.vcfPhone) &&
        equalsNullable(this.code, attachmentRequestPayload.code) &&
        equalsNullable(this.buttons, attachmentRequestPayload.buttons);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(token), hashCodeNullable(url), hashCodeNullable(photos), hashCodeNullable(name), hashCodeNullable(contactId), hashCodeNullable(vcfInfo), hashCodeNullable(vcfPhone), hashCodeNullable(code), hashCodeNullable(buttons));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentRequestPayload {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    photos: ").append(toIndentedString(photos)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    vcfInfo: ").append(toIndentedString(vcfInfo)).append("\n");
    sb.append("    vcfPhone: ").append(toIndentedString(vcfPhone)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    buttons: ").append(toIndentedString(buttons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

