/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.BotCommand;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Объект включает общую информацию о боте, URL аватара и описание. Дополнительно содержит список команд, поддерживаемых ботом. Возвращается только при вызове метода GET/me  Источник описания: [BotInfo](https://dev.max.ru/docs-api/objects/BotInfo)
 */
@JsonPropertyOrder({
  BotInfo.JSON_PROPERTY_USER_ID,
  BotInfo.JSON_PROPERTY_FIRST_NAME,
  BotInfo.JSON_PROPERTY_LAST_NAME,
  BotInfo.JSON_PROPERTY_USERNAME,
  BotInfo.JSON_PROPERTY_IS_BOT,
  BotInfo.JSON_PROPERTY_LAST_ACTIVITY_TIME,
  BotInfo.JSON_PROPERTY_NAME,
  BotInfo.JSON_PROPERTY_DESCRIPTION,
  BotInfo.JSON_PROPERTY_AVATAR_URL,
  BotInfo.JSON_PROPERTY_FULL_AVATAR_URL,
  BotInfo.JSON_PROPERTY_COMMANDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class BotInfo {
  public static final String JSON_PROPERTY_USER_ID = "user_id";
  @jakarta.annotation.Nonnull
  private Integer userId;

  public static final String JSON_PROPERTY_FIRST_NAME = "first_name";
  @jakarta.annotation.Nonnull
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "last_name";
  @jakarta.annotation.Nullable
  private JsonNullable<String> lastName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_USERNAME = "username";
  @jakarta.annotation.Nullable
  private JsonNullable<String> username = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IS_BOT = "is_bot";
  @jakarta.annotation.Nonnull
  private Boolean isBot;

  public static final String JSON_PROPERTY_LAST_ACTIVITY_TIME = "last_activity_time";
  @jakarta.annotation.Nonnull
  private Integer lastActivityTime;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AVATAR_URL = "avatar_url";
  @jakarta.annotation.Nullable
  private String avatarUrl;

  public static final String JSON_PROPERTY_FULL_AVATAR_URL = "full_avatar_url";
  @jakarta.annotation.Nullable
  private String fullAvatarUrl;

  public static final String JSON_PROPERTY_COMMANDS = "commands";
  @jakarta.annotation.Nullable
  private JsonNullable<List<BotCommand>> commands = JsonNullable.<List<BotCommand>>undefined();

  public BotInfo() {
  }

  public BotInfo userId(@jakarta.annotation.Nonnull Integer userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Идентификатор пользователя или бота
   * @return userId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@jakarta.annotation.Nonnull Integer userId) {
    this.userId = userId;
  }

  public BotInfo firstName(@jakarta.annotation.Nonnull String firstName) {
    
    this.firstName = firstName;
    return this;
  }

  /**
   * Отображаемое имя пользователя или бота
   * @return firstName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirstName(@jakarta.annotation.Nonnull String firstName) {
    this.firstName = firstName;
  }

  public BotInfo lastName(@jakarta.annotation.Nullable String lastName) {
    this.lastName = JsonNullable.<String>of(lastName);
    
    return this;
  }

  /**
   * Отображаемая фамилия пользователя. Для ботов это поле не возвращается
   * @return lastName
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLastName() {
        return lastName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastName_JsonNullable() {
    return lastName;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  public void setLastName_JsonNullable(JsonNullable<String> lastName) {
    this.lastName = lastName;
  }

  public void setLastName(@jakarta.annotation.Nullable String lastName) {
    this.lastName = JsonNullable.<String>of(lastName);
  }

  public BotInfo username(@jakarta.annotation.Nullable String username) {
    this.username = JsonNullable.<String>of(username);
    
    return this;
  }

  /**
   * Никнейм бота или уникальное публичное имя пользователя. В случае с пользователем может быть null, если тот недоступен или имя не задано
   * @return username
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getUsername() {
        return username.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUsername_JsonNullable() {
    return username;
  }
  
  @JsonProperty(JSON_PROPERTY_USERNAME)
  public void setUsername_JsonNullable(JsonNullable<String> username) {
    this.username = username;
  }

  public void setUsername(@jakarta.annotation.Nullable String username) {
    this.username = JsonNullable.<String>of(username);
  }

  public BotInfo isBot(@jakarta.annotation.Nonnull Boolean isBot) {
    
    this.isBot = isBot;
    return this;
  }

  /**
   * true, если это бот
   * @return isBot
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_BOT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsBot() {
    return isBot;
  }


  @JsonProperty(JSON_PROPERTY_IS_BOT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsBot(@jakarta.annotation.Nonnull Boolean isBot) {
    this.isBot = isBot;
  }

  public BotInfo lastActivityTime(@jakarta.annotation.Nonnull Integer lastActivityTime) {
    
    this.lastActivityTime = lastActivityTime;
    return this;
  }

  /**
   * Время последней активности пользователя или бота в MAX (Unix-время в миллисекундах). Если пользователь отключил в настройках профиля мессенджера MAX возможность видеть, что он в сети онлайн, поле может не возвращаться
   * @return lastActivityTime
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getLastActivityTime() {
    return lastActivityTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastActivityTime(@jakarta.annotation.Nonnull Integer lastActivityTime) {
    this.lastActivityTime = lastActivityTime;
  }

  public BotInfo name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    
    return this;
  }

  /**
   * Устаревшее поле, скоро будет удалено
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }

  public BotInfo description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * до 16000 символов Описание пользователя или бота. В случае с пользователем может принимать значение null, если описание не заполнено
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  public BotInfo avatarUrl(@jakarta.annotation.Nullable String avatarUrl) {
    
    this.avatarUrl = avatarUrl;
    return this;
  }

  /**
   * URL аватара пользователя или бота в уменьшенном размере
   * @return avatarUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAvatarUrl() {
    return avatarUrl;
  }


  @JsonProperty(JSON_PROPERTY_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvatarUrl(@jakarta.annotation.Nullable String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }

  public BotInfo fullAvatarUrl(@jakarta.annotation.Nullable String fullAvatarUrl) {
    
    this.fullAvatarUrl = fullAvatarUrl;
    return this;
  }

  /**
   * URL аватара пользователя или бота в полном размере
   * @return fullAvatarUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULL_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFullAvatarUrl() {
    return fullAvatarUrl;
  }


  @JsonProperty(JSON_PROPERTY_FULL_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullAvatarUrl(@jakarta.annotation.Nullable String fullAvatarUrl) {
    this.fullAvatarUrl = fullAvatarUrl;
  }

  public BotInfo commands(@jakarta.annotation.Nullable List<BotCommand> commands) {
    this.commands = JsonNullable.<List<BotCommand>>of(commands);
    
    return this;
  }

  public BotInfo addCommandsItem(BotCommand commandsItem) {
    if (this.commands == null || !this.commands.isPresent()) {
      this.commands = JsonNullable.<List<BotCommand>>of(new ArrayList<>());
    }
    try {
      this.commands.get().add(commandsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * до 32 элементов Команды, поддерживаемые ботом
   * @return commands
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<BotCommand> getCommands() {
        return commands.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMMANDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<BotCommand>> getCommands_JsonNullable() {
    return commands;
  }
  
  @JsonProperty(JSON_PROPERTY_COMMANDS)
  public void setCommands_JsonNullable(JsonNullable<List<BotCommand>> commands) {
    this.commands = commands;
  }

  public void setCommands(@jakarta.annotation.Nullable List<BotCommand> commands) {
    this.commands = JsonNullable.<List<BotCommand>>of(commands);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BotInfo botInfo = (BotInfo) o;
    return Objects.equals(this.userId, botInfo.userId) &&
        Objects.equals(this.firstName, botInfo.firstName) &&
        equalsNullable(this.lastName, botInfo.lastName) &&
        equalsNullable(this.username, botInfo.username) &&
        Objects.equals(this.isBot, botInfo.isBot) &&
        Objects.equals(this.lastActivityTime, botInfo.lastActivityTime) &&
        equalsNullable(this.name, botInfo.name) &&
        equalsNullable(this.description, botInfo.description) &&
        Objects.equals(this.avatarUrl, botInfo.avatarUrl) &&
        Objects.equals(this.fullAvatarUrl, botInfo.fullAvatarUrl) &&
        equalsNullable(this.commands, botInfo.commands);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, firstName, hashCodeNullable(lastName), hashCodeNullable(username), isBot, lastActivityTime, hashCodeNullable(name), hashCodeNullable(description), avatarUrl, fullAvatarUrl, hashCodeNullable(commands));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BotInfo {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    isBot: ").append(toIndentedString(isBot)).append("\n");
    sb.append("    lastActivityTime: ").append(toIndentedString(lastActivityTime)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("    fullAvatarUrl: ").append(toIndentedString(fullAvatarUrl)).append("\n");
    sb.append("    commands: ").append(toIndentedString(commands)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

