/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Источник описания: [POST /chats/{chatId}/members/admins](https://dev.max.ru/docs-api/methods/POST/chats/-chatId-/members/admins)
 */
@JsonPropertyOrder({
  ChatAdmin.JSON_PROPERTY_USER_ID,
  ChatAdmin.JSON_PROPERTY_PERMISSIONS,
  ChatAdmin.JSON_PROPERTY_ALIAS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class ChatAdmin {
  public static final String JSON_PROPERTY_USER_ID = "user_id";
  @jakarta.annotation.Nonnull
  private Integer userId;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @jakarta.annotation.Nullable
  private JsonNullable<List<Map<String, Object>>> permissions = JsonNullable.<List<Map<String, Object>>>undefined();

  public static final String JSON_PROPERTY_ALIAS = "alias";
  @jakarta.annotation.Nullable
  private JsonNullable<String> alias = JsonNullable.<String>undefined();

  public ChatAdmin() {
  }

  public ChatAdmin userId(@jakarta.annotation.Nonnull Integer userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * ID пользователя
   * @return userId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@jakarta.annotation.Nonnull Integer userId) {
    this.userId = userId;
  }

  public ChatAdmin permissions(@jakarta.annotation.Nullable List<Map<String, Object>> permissions) {
    this.permissions = JsonNullable.<List<Map<String, Object>>>of(permissions);
    
    return this;
  }

  public ChatAdmin addPermissionsItem(Map<String, Object> permissionsItem) {
    if (this.permissions == null || !this.permissions.isPresent()) {
      this.permissions = JsonNullable.<List<Map<String, Object>>>of(new ArrayList<>());
    }
    try {
      this.permissions.get().add(permissionsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Права администратора
   * @return permissions
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<Map<String, Object>> getPermissions() {
        return permissions.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Map<String, Object>>> getPermissions_JsonNullable() {
    return permissions;
  }
  
  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  public void setPermissions_JsonNullable(JsonNullable<List<Map<String, Object>>> permissions) {
    this.permissions = permissions;
  }

  public void setPermissions(@jakarta.annotation.Nullable List<Map<String, Object>> permissions) {
    this.permissions = JsonNullable.<List<Map<String, Object>>>of(permissions);
  }

  public ChatAdmin alias(@jakarta.annotation.Nullable String alias) {
    this.alias = JsonNullable.<String>of(alias);
    
    return this;
  }

  /**
   * Псевдоним администратора
   * @return alias
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getAlias() {
        return alias.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAlias_JsonNullable() {
    return alias;
  }
  
  @JsonProperty(JSON_PROPERTY_ALIAS)
  public void setAlias_JsonNullable(JsonNullable<String> alias) {
    this.alias = alias;
  }

  public void setAlias(@jakarta.annotation.Nullable String alias) {
    this.alias = JsonNullable.<String>of(alias);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatAdmin chatAdmin = (ChatAdmin) o;
    return Objects.equals(this.userId, chatAdmin.userId) &&
        equalsNullable(this.permissions, chatAdmin.permissions) &&
        equalsNullable(this.alias, chatAdmin.alias);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, hashCodeNullable(permissions), hashCodeNullable(alias));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatAdmin {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

