/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.Image;
import ru.golshansky.maxbotapi.client.model.Message;
import ru.golshansky.maxbotapi.client.model.UserWithPhoto;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Источник описания: [Chat](https://dev.max.ru/docs-api/objects/Chat)
 */
@JsonPropertyOrder({
  Chat.JSON_PROPERTY_CHAT_ID,
  Chat.JSON_PROPERTY_TYPE,
  Chat.JSON_PROPERTY_STATUS,
  Chat.JSON_PROPERTY_TITLE,
  Chat.JSON_PROPERTY_ICON,
  Chat.JSON_PROPERTY_LAST_EVENT_TIME,
  Chat.JSON_PROPERTY_PARTICIPANTS_COUNT,
  Chat.JSON_PROPERTY_OWNER_ID,
  Chat.JSON_PROPERTY_PARTICIPANTS,
  Chat.JSON_PROPERTY_IS_PUBLIC,
  Chat.JSON_PROPERTY_LINK,
  Chat.JSON_PROPERTY_DESCRIPTION,
  Chat.JSON_PROPERTY_DIALOG_WITH_USER,
  Chat.JSON_PROPERTY_CHAT_MESSAGE_ID,
  Chat.JSON_PROPERTY_PINNED_MESSAGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class Chat {
  public static final String JSON_PROPERTY_CHAT_ID = "chat_id";
  @jakarta.annotation.Nonnull
  private Integer chatId;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private String type;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private String status;

  public static final String JSON_PROPERTY_TITLE = "title";
  @jakarta.annotation.Nullable
  private JsonNullable<String> title = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ICON = "icon";
  @jakarta.annotation.Nullable
  private Image icon;

  public static final String JSON_PROPERTY_LAST_EVENT_TIME = "last_event_time";
  @jakarta.annotation.Nonnull
  private Integer lastEventTime;

  public static final String JSON_PROPERTY_PARTICIPANTS_COUNT = "participants_count";
  @jakarta.annotation.Nonnull
  private Integer participantsCount;

  public static final String JSON_PROPERTY_OWNER_ID = "owner_id";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> ownerId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_PARTICIPANTS = "participants";
  @jakarta.annotation.Nullable
  private JsonNullable<Object> participants = JsonNullable.<Object>undefined();

  public static final String JSON_PROPERTY_IS_PUBLIC = "is_public";
  @jakarta.annotation.Nonnull
  private Boolean isPublic;

  public static final String JSON_PROPERTY_LINK = "link";
  @jakarta.annotation.Nullable
  private JsonNullable<String> link = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DIALOG_WITH_USER = "dialog_with_user";
  @jakarta.annotation.Nullable
  private UserWithPhoto dialogWithUser;

  public static final String JSON_PROPERTY_CHAT_MESSAGE_ID = "chat_message_id";
  @jakarta.annotation.Nullable
  private JsonNullable<String> chatMessageId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PINNED_MESSAGE = "pinned_message";
  @jakarta.annotation.Nullable
  private Message pinnedMessage;

  public Chat() {
  }

  public Chat chatId(@jakarta.annotation.Nonnull Integer chatId) {
    
    this.chatId = chatId;
    return this;
  }

  /**
   * ID чата
   * @return chatId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHAT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getChatId() {
    return chatId;
  }


  @JsonProperty(JSON_PROPERTY_CHAT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChatId(@jakarta.annotation.Nonnull Integer chatId) {
    this.chatId = chatId;
  }

  public Chat type(@jakarta.annotation.Nonnull String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Enum:  \&quot;chat\&quot;  Тип чата:  \&quot;chat\&quot; — Групповой чат \&quot;channel\&quot; — Канал \&quot;dialog\&quot; — Диалог
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull String type) {
    this.type = type;
  }

  public Chat status(@jakarta.annotation.Nonnull String status) {
    
    this.status = status;
    return this;
  }

  /**
   * Enum:  \&quot;active\&quot; \&quot;removed\&quot; \&quot;left\&quot; \&quot;closed\&quot;  Статус чата:  \&quot;active\&quot; — Бот является активным участником чата \&quot;removed\&quot; — Бот был удалён из чата \&quot;left\&quot; — Бот покинул чат \&quot;closed\&quot; — Чат был закрыт
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull String status) {
    this.status = status;
  }

  public Chat title(@jakarta.annotation.Nullable String title) {
    this.title = JsonNullable.<String>of(title);
    
    return this;
  }

  /**
   * Отображаемое название чата. Может быть null для диалогов
   * @return title
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getTitle() {
        return title.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTitle_JsonNullable() {
    return title;
  }
  
  @JsonProperty(JSON_PROPERTY_TITLE)
  public void setTitle_JsonNullable(JsonNullable<String> title) {
    this.title = title;
  }

  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = JsonNullable.<String>of(title);
  }

  public Chat icon(@jakarta.annotation.Nullable Image icon) {
    
    this.icon = icon;
    return this;
  }

  /**
   * Get icon
   * @return icon
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ICON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Image getIcon() {
    return icon;
  }


  @JsonProperty(JSON_PROPERTY_ICON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIcon(@jakarta.annotation.Nullable Image icon) {
    this.icon = icon;
  }

  public Chat lastEventTime(@jakarta.annotation.Nonnull Integer lastEventTime) {
    
    this.lastEventTime = lastEventTime;
    return this;
  }

  /**
   * Время последнего события в чате
   * @return lastEventTime
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAST_EVENT_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getLastEventTime() {
    return lastEventTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_EVENT_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastEventTime(@jakarta.annotation.Nonnull Integer lastEventTime) {
    this.lastEventTime = lastEventTime;
  }

  public Chat participantsCount(@jakarta.annotation.Nonnull Integer participantsCount) {
    
    this.participantsCount = participantsCount;
    return this;
  }

  /**
   * Количество участников чата. Для диалогов всегда 2
   * @return participantsCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARTICIPANTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getParticipantsCount() {
    return participantsCount;
  }


  @JsonProperty(JSON_PROPERTY_PARTICIPANTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParticipantsCount(@jakarta.annotation.Nonnull Integer participantsCount) {
    this.participantsCount = participantsCount;
  }

  public Chat ownerId(@jakarta.annotation.Nullable Integer ownerId) {
    this.ownerId = JsonNullable.<Integer>of(ownerId);
    
    return this;
  }

  /**
   * ID владельца чата
   * @return ownerId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getOwnerId() {
        return ownerId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getOwnerId_JsonNullable() {
    return ownerId;
  }
  
  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  public void setOwnerId_JsonNullable(JsonNullable<Integer> ownerId) {
    this.ownerId = ownerId;
  }

  public void setOwnerId(@jakarta.annotation.Nullable Integer ownerId) {
    this.ownerId = JsonNullable.<Integer>of(ownerId);
  }

  public Chat participants(@jakarta.annotation.Nullable Object participants) {
    this.participants = JsonNullable.<Object>of(participants);
    
    return this;
  }

  /**
   * Участники чата с временем последней активности. Может быть null, если запрашивается список чатов
   * @return participants
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getParticipants() {
        return participants.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PARTICIPANTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getParticipants_JsonNullable() {
    return participants;
  }
  
  @JsonProperty(JSON_PROPERTY_PARTICIPANTS)
  public void setParticipants_JsonNullable(JsonNullable<Object> participants) {
    this.participants = participants;
  }

  public void setParticipants(@jakarta.annotation.Nullable Object participants) {
    this.participants = JsonNullable.<Object>of(participants);
  }

  public Chat isPublic(@jakarta.annotation.Nonnull Boolean isPublic) {
    
    this.isPublic = isPublic;
    return this;
  }

  /**
   * Доступен ли чат публично (для диалогов всегда false  Шаблон: &#x60;)&#x60;
   * @return isPublic
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsPublic() {
    return isPublic;
  }


  @JsonProperty(JSON_PROPERTY_IS_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsPublic(@jakarta.annotation.Nonnull Boolean isPublic) {
    this.isPublic = isPublic;
  }

  public Chat link(@jakarta.annotation.Nullable String link) {
    this.link = JsonNullable.<String>of(link);
    
    return this;
  }

  /**
   * Ссылка на чат
   * @return link
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLink() {
        return link.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLink_JsonNullable() {
    return link;
  }
  
  @JsonProperty(JSON_PROPERTY_LINK)
  public void setLink_JsonNullable(JsonNullable<String> link) {
    this.link = link;
  }

  public void setLink(@jakarta.annotation.Nullable String link) {
    this.link = JsonNullable.<String>of(link);
  }

  public Chat description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * Описание чата
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  public Chat dialogWithUser(@jakarta.annotation.Nullable UserWithPhoto dialogWithUser) {
    
    this.dialogWithUser = dialogWithUser;
    return this;
  }

  /**
   * Get dialogWithUser
   * @return dialogWithUser
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIALOG_WITH_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserWithPhoto getDialogWithUser() {
    return dialogWithUser;
  }


  @JsonProperty(JSON_PROPERTY_DIALOG_WITH_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDialogWithUser(@jakarta.annotation.Nullable UserWithPhoto dialogWithUser) {
    this.dialogWithUser = dialogWithUser;
  }

  public Chat chatMessageId(@jakarta.annotation.Nullable String chatMessageId) {
    this.chatMessageId = JsonNullable.<String>of(chatMessageId);
    
    return this;
  }

  /**
   * ID сообщения, содержащего кнопку, через которую был инициирован чат
   * @return chatMessageId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getChatMessageId() {
        return chatMessageId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CHAT_MESSAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getChatMessageId_JsonNullable() {
    return chatMessageId;
  }
  
  @JsonProperty(JSON_PROPERTY_CHAT_MESSAGE_ID)
  public void setChatMessageId_JsonNullable(JsonNullable<String> chatMessageId) {
    this.chatMessageId = chatMessageId;
  }

  public void setChatMessageId(@jakarta.annotation.Nullable String chatMessageId) {
    this.chatMessageId = JsonNullable.<String>of(chatMessageId);
  }

  public Chat pinnedMessage(@jakarta.annotation.Nullable Message pinnedMessage) {
    
    this.pinnedMessage = pinnedMessage;
    return this;
  }

  /**
   * Get pinnedMessage
   * @return pinnedMessage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PINNED_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Message getPinnedMessage() {
    return pinnedMessage;
  }


  @JsonProperty(JSON_PROPERTY_PINNED_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPinnedMessage(@jakarta.annotation.Nullable Message pinnedMessage) {
    this.pinnedMessage = pinnedMessage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Chat chat = (Chat) o;
    return Objects.equals(this.chatId, chat.chatId) &&
        Objects.equals(this.type, chat.type) &&
        Objects.equals(this.status, chat.status) &&
        equalsNullable(this.title, chat.title) &&
        Objects.equals(this.icon, chat.icon) &&
        Objects.equals(this.lastEventTime, chat.lastEventTime) &&
        Objects.equals(this.participantsCount, chat.participantsCount) &&
        equalsNullable(this.ownerId, chat.ownerId) &&
        equalsNullable(this.participants, chat.participants) &&
        Objects.equals(this.isPublic, chat.isPublic) &&
        equalsNullable(this.link, chat.link) &&
        equalsNullable(this.description, chat.description) &&
        Objects.equals(this.dialogWithUser, chat.dialogWithUser) &&
        equalsNullable(this.chatMessageId, chat.chatMessageId) &&
        Objects.equals(this.pinnedMessage, chat.pinnedMessage);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(chatId, type, status, hashCodeNullable(title), icon, lastEventTime, participantsCount, hashCodeNullable(ownerId), hashCodeNullable(participants), isPublic, hashCodeNullable(link), hashCodeNullable(description), dialogWithUser, hashCodeNullable(chatMessageId), pinnedMessage);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Chat {\n");
    sb.append("    chatId: ").append(toIndentedString(chatId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    lastEventTime: ").append(toIndentedString(lastEventTime)).append("\n");
    sb.append("    participantsCount: ").append(toIndentedString(participantsCount)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    participants: ").append(toIndentedString(participants)).append("\n");
    sb.append("    isPublic: ").append(toIndentedString(isPublic)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    dialogWithUser: ").append(toIndentedString(dialogWithUser)).append("\n");
    sb.append("    chatMessageId: ").append(toIndentedString(chatMessageId)).append("\n");
    sb.append("    pinnedMessage: ").append(toIndentedString(pinnedMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

