/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Объект включает общую информацию о пользователе или боте, URL аватара и описание (при наличии). Дополнительно содержит данные для пользователей-участников чата. Возвращается только при вызове некоторых методов группы/chats, например GET/chats/{chatId}/members  Источник описания: [ChatMember](https://dev.max.ru/docs-api/objects/ChatMember)
 */
@JsonPropertyOrder({
  ChatMember.JSON_PROPERTY_USER_ID,
  ChatMember.JSON_PROPERTY_FIRST_NAME,
  ChatMember.JSON_PROPERTY_LAST_NAME,
  ChatMember.JSON_PROPERTY_USERNAME,
  ChatMember.JSON_PROPERTY_IS_BOT,
  ChatMember.JSON_PROPERTY_LAST_ACTIVITY_TIME,
  ChatMember.JSON_PROPERTY_NAME,
  ChatMember.JSON_PROPERTY_DESCRIPTION,
  ChatMember.JSON_PROPERTY_AVATAR_URL,
  ChatMember.JSON_PROPERTY_FULL_AVATAR_URL,
  ChatMember.JSON_PROPERTY_LAST_ACCESS_TIME,
  ChatMember.JSON_PROPERTY_IS_OWNER,
  ChatMember.JSON_PROPERTY_IS_ADMIN,
  ChatMember.JSON_PROPERTY_JOIN_TIME,
  ChatMember.JSON_PROPERTY_PERMISSIONS,
  ChatMember.JSON_PROPERTY_ALIAS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class ChatMember {
  public static final String JSON_PROPERTY_USER_ID = "user_id";
  @jakarta.annotation.Nonnull
  private Integer userId;

  public static final String JSON_PROPERTY_FIRST_NAME = "first_name";
  @jakarta.annotation.Nonnull
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "last_name";
  @jakarta.annotation.Nullable
  private JsonNullable<String> lastName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_USERNAME = "username";
  @jakarta.annotation.Nullable
  private JsonNullable<String> username = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IS_BOT = "is_bot";
  @jakarta.annotation.Nonnull
  private Boolean isBot;

  public static final String JSON_PROPERTY_LAST_ACTIVITY_TIME = "last_activity_time";
  @jakarta.annotation.Nonnull
  private Integer lastActivityTime;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AVATAR_URL = "avatar_url";
  @jakarta.annotation.Nullable
  private String avatarUrl;

  public static final String JSON_PROPERTY_FULL_AVATAR_URL = "full_avatar_url";
  @jakarta.annotation.Nullable
  private String fullAvatarUrl;

  public static final String JSON_PROPERTY_LAST_ACCESS_TIME = "last_access_time";
  @jakarta.annotation.Nonnull
  private Integer lastAccessTime;

  public static final String JSON_PROPERTY_IS_OWNER = "is_owner";
  @jakarta.annotation.Nonnull
  private Boolean isOwner;

  public static final String JSON_PROPERTY_IS_ADMIN = "is_admin";
  @jakarta.annotation.Nonnull
  private Boolean isAdmin;

  public static final String JSON_PROPERTY_JOIN_TIME = "join_time";
  @jakarta.annotation.Nonnull
  private Integer joinTime;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @jakarta.annotation.Nullable
  private JsonNullable<List<Map<String, Object>>> permissions = JsonNullable.<List<Map<String, Object>>>undefined();

  public static final String JSON_PROPERTY_ALIAS = "alias";
  @jakarta.annotation.Nullable
  private String alias;

  public ChatMember() {
  }

  public ChatMember userId(@jakarta.annotation.Nonnull Integer userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Идентификатор пользователя или бота
   * @return userId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@jakarta.annotation.Nonnull Integer userId) {
    this.userId = userId;
  }

  public ChatMember firstName(@jakarta.annotation.Nonnull String firstName) {
    
    this.firstName = firstName;
    return this;
  }

  /**
   * Отображаемое имя пользователя или бота
   * @return firstName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirstName(@jakarta.annotation.Nonnull String firstName) {
    this.firstName = firstName;
  }

  public ChatMember lastName(@jakarta.annotation.Nullable String lastName) {
    this.lastName = JsonNullable.<String>of(lastName);
    
    return this;
  }

  /**
   * Отображаемая фамилия пользователя. Для ботов это поле не возвращается
   * @return lastName
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLastName() {
        return lastName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastName_JsonNullable() {
    return lastName;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  public void setLastName_JsonNullable(JsonNullable<String> lastName) {
    this.lastName = lastName;
  }

  public void setLastName(@jakarta.annotation.Nullable String lastName) {
    this.lastName = JsonNullable.<String>of(lastName);
  }

  public ChatMember username(@jakarta.annotation.Nullable String username) {
    this.username = JsonNullable.<String>of(username);
    
    return this;
  }

  /**
   * Никнейм бота или уникальное публичное имя пользователя. В случае с пользователем может быть null, если тот недоступен или имя не задано
   * @return username
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getUsername() {
        return username.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUsername_JsonNullable() {
    return username;
  }
  
  @JsonProperty(JSON_PROPERTY_USERNAME)
  public void setUsername_JsonNullable(JsonNullable<String> username) {
    this.username = username;
  }

  public void setUsername(@jakarta.annotation.Nullable String username) {
    this.username = JsonNullable.<String>of(username);
  }

  public ChatMember isBot(@jakarta.annotation.Nonnull Boolean isBot) {
    
    this.isBot = isBot;
    return this;
  }

  /**
   * true, если это бот
   * @return isBot
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_BOT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsBot() {
    return isBot;
  }


  @JsonProperty(JSON_PROPERTY_IS_BOT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsBot(@jakarta.annotation.Nonnull Boolean isBot) {
    this.isBot = isBot;
  }

  public ChatMember lastActivityTime(@jakarta.annotation.Nonnull Integer lastActivityTime) {
    
    this.lastActivityTime = lastActivityTime;
    return this;
  }

  /**
   * Время последней активности пользователя или бота в MAX (Unix-время в миллисекундах). Если пользователь отключил в настройках профиля мессенджера MAX возможность видеть, что он в сети онлайн, поле может не возвращаться
   * @return lastActivityTime
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getLastActivityTime() {
    return lastActivityTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastActivityTime(@jakarta.annotation.Nonnull Integer lastActivityTime) {
    this.lastActivityTime = lastActivityTime;
  }

  public ChatMember name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    
    return this;
  }

  /**
   * Устаревшее поле, скоро будет удалено
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }

  public ChatMember description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * до 16000 символов Описание пользователя или бота. В случае с пользователем может принимать значение null, если описание не заполнено
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  public ChatMember avatarUrl(@jakarta.annotation.Nullable String avatarUrl) {
    
    this.avatarUrl = avatarUrl;
    return this;
  }

  /**
   * URL аватара пользователя или бота в уменьшенном размере
   * @return avatarUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAvatarUrl() {
    return avatarUrl;
  }


  @JsonProperty(JSON_PROPERTY_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvatarUrl(@jakarta.annotation.Nullable String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }

  public ChatMember fullAvatarUrl(@jakarta.annotation.Nullable String fullAvatarUrl) {
    
    this.fullAvatarUrl = fullAvatarUrl;
    return this;
  }

  /**
   * URL аватара пользователя или бота в полном размере
   * @return fullAvatarUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULL_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFullAvatarUrl() {
    return fullAvatarUrl;
  }


  @JsonProperty(JSON_PROPERTY_FULL_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullAvatarUrl(@jakarta.annotation.Nullable String fullAvatarUrl) {
    this.fullAvatarUrl = fullAvatarUrl;
  }

  public ChatMember lastAccessTime(@jakarta.annotation.Nonnull Integer lastAccessTime) {
    
    this.lastAccessTime = lastAccessTime;
    return this;
  }

  /**
   * Время последней активности пользователя в чате. Может быть устаревшим для суперчатов (равно времени вступления)
   * @return lastAccessTime
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAST_ACCESS_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getLastAccessTime() {
    return lastAccessTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ACCESS_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastAccessTime(@jakarta.annotation.Nonnull Integer lastAccessTime) {
    this.lastAccessTime = lastAccessTime;
  }

  public ChatMember isOwner(@jakarta.annotation.Nonnull Boolean isOwner) {
    
    this.isOwner = isOwner;
    return this;
  }

  /**
   * Является ли пользователь владельцем чата
   * @return isOwner
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_OWNER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsOwner() {
    return isOwner;
  }


  @JsonProperty(JSON_PROPERTY_IS_OWNER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsOwner(@jakarta.annotation.Nonnull Boolean isOwner) {
    this.isOwner = isOwner;
  }

  public ChatMember isAdmin(@jakarta.annotation.Nonnull Boolean isAdmin) {
    
    this.isAdmin = isAdmin;
    return this;
  }

  /**
   * Является ли пользователь администратором чата
   * @return isAdmin
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_ADMIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsAdmin() {
    return isAdmin;
  }


  @JsonProperty(JSON_PROPERTY_IS_ADMIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsAdmin(@jakarta.annotation.Nonnull Boolean isAdmin) {
    this.isAdmin = isAdmin;
  }

  public ChatMember joinTime(@jakarta.annotation.Nonnull Integer joinTime) {
    
    this.joinTime = joinTime;
    return this;
  }

  /**
   * Дата присоединения к чату в формате Unix time
   * @return joinTime
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_JOIN_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getJoinTime() {
    return joinTime;
  }


  @JsonProperty(JSON_PROPERTY_JOIN_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setJoinTime(@jakarta.annotation.Nonnull Integer joinTime) {
    this.joinTime = joinTime;
  }

  public ChatMember permissions(@jakarta.annotation.Nullable List<Map<String, Object>> permissions) {
    this.permissions = JsonNullable.<List<Map<String, Object>>>of(permissions);
    
    return this;
  }

  public ChatMember addPermissionsItem(Map<String, Object> permissionsItem) {
    if (this.permissions == null || !this.permissions.isPresent()) {
      this.permissions = JsonNullable.<List<Map<String, Object>>>of(new ArrayList<>());
    }
    try {
      this.permissions.get().add(permissionsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Items Enum:  \&quot;read_all_messages\&quot; \&quot;add_remove_members\&quot; \&quot;add_admins\&quot; \&quot;change_chat_info\&quot; \&quot;pin_message\&quot; \&quot;write\&quot; \&quot;can_call\&quot; \&quot;edit_link\&quot; \&quot;post_edit_delete_message\&quot; \&quot;edit_message\&quot; \&quot;delete_message\&quot;  Перечень прав пользователя. Возможные значения:  \&quot;read_all_messages\&quot; — Читать все сообщения. \&quot;add_remove_members\&quot; — Добавлять/удалять участников. \&quot;add_admins\&quot; — Добавлять администраторов. \&quot;change_chat_info\&quot; — Изменять информацию о чате. \&quot;pin_message\&quot; — Закреплять сообщения. \&quot;write\&quot; — Писать сообщения. \&quot;edit_link\&quot; — Изменять ссылку на чат.
   * @return permissions
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<Map<String, Object>> getPermissions() {
        return permissions.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Map<String, Object>>> getPermissions_JsonNullable() {
    return permissions;
  }
  
  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  public void setPermissions_JsonNullable(JsonNullable<List<Map<String, Object>>> permissions) {
    this.permissions = permissions;
  }

  public void setPermissions(@jakarta.annotation.Nullable List<Map<String, Object>> permissions) {
    this.permissions = JsonNullable.<List<Map<String, Object>>>of(permissions);
  }

  public ChatMember alias(@jakarta.annotation.Nullable String alias) {
    
    this.alias = alias;
    return this;
  }

  /**
   * Заголовок, который будет показан на клиенте  Если пользователь администратор или владелец и ему не установлено это название, то поле не передаётся, клиенты на своей стороне подменят на \&quot;владелец\&quot; или \&quot;админ\&quot;
   * @return alias
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlias() {
    return alias;
  }


  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlias(@jakarta.annotation.Nullable String alias) {
    this.alias = alias;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatMember chatMember = (ChatMember) o;
    return Objects.equals(this.userId, chatMember.userId) &&
        Objects.equals(this.firstName, chatMember.firstName) &&
        equalsNullable(this.lastName, chatMember.lastName) &&
        equalsNullable(this.username, chatMember.username) &&
        Objects.equals(this.isBot, chatMember.isBot) &&
        Objects.equals(this.lastActivityTime, chatMember.lastActivityTime) &&
        equalsNullable(this.name, chatMember.name) &&
        equalsNullable(this.description, chatMember.description) &&
        Objects.equals(this.avatarUrl, chatMember.avatarUrl) &&
        Objects.equals(this.fullAvatarUrl, chatMember.fullAvatarUrl) &&
        Objects.equals(this.lastAccessTime, chatMember.lastAccessTime) &&
        Objects.equals(this.isOwner, chatMember.isOwner) &&
        Objects.equals(this.isAdmin, chatMember.isAdmin) &&
        Objects.equals(this.joinTime, chatMember.joinTime) &&
        equalsNullable(this.permissions, chatMember.permissions) &&
        Objects.equals(this.alias, chatMember.alias);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, firstName, hashCodeNullable(lastName), hashCodeNullable(username), isBot, lastActivityTime, hashCodeNullable(name), hashCodeNullable(description), avatarUrl, fullAvatarUrl, lastAccessTime, isOwner, isAdmin, joinTime, hashCodeNullable(permissions), alias);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatMember {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    isBot: ").append(toIndentedString(isBot)).append("\n");
    sb.append("    lastActivityTime: ").append(toIndentedString(lastActivityTime)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("    fullAvatarUrl: ").append(toIndentedString(fullAvatarUrl)).append("\n");
    sb.append("    lastAccessTime: ").append(toIndentedString(lastAccessTime)).append("\n");
    sb.append("    isOwner: ").append(toIndentedString(isOwner)).append("\n");
    sb.append("    isAdmin: ").append(toIndentedString(isAdmin)).append("\n");
    sb.append("    joinTime: ").append(toIndentedString(joinTime)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

