/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.ChatMember;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetChatsByChatIdMembers200Response
 */
@JsonPropertyOrder({
  GetChatsByChatIdMembers200Response.JSON_PROPERTY_MEMBERS,
  GetChatsByChatIdMembers200Response.JSON_PROPERTY_MARKER
})
@JsonTypeName("get_chats_by_chatId_members_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class GetChatsByChatIdMembers200Response {
  public static final String JSON_PROPERTY_MEMBERS = "members";
  @jakarta.annotation.Nonnull
  private List<ChatMember> members = new ArrayList<>();

  public static final String JSON_PROPERTY_MARKER = "marker";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> marker = JsonNullable.<Integer>undefined();

  public GetChatsByChatIdMembers200Response() {
  }

  public GetChatsByChatIdMembers200Response members(@jakarta.annotation.Nonnull List<ChatMember> members) {
    
    this.members = members;
    return this;
  }

  public GetChatsByChatIdMembers200Response addMembersItem(ChatMember membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<>();
    }
    this.members.add(membersItem);
    return this;
  }

  /**
   * Список участников чата с информацией о времени последней активности
   * @return members
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MEMBERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ChatMember> getMembers() {
    return members;
  }


  @JsonProperty(JSON_PROPERTY_MEMBERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMembers(@jakarta.annotation.Nonnull List<ChatMember> members) {
    this.members = members;
  }

  public GetChatsByChatIdMembers200Response marker(@jakarta.annotation.Nullable Integer marker) {
    this.marker = JsonNullable.<Integer>of(marker);
    
    return this;
  }

  /**
   * Указатель на следующую страницу данных
   * @return marker
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getMarker() {
        return marker.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MARKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getMarker_JsonNullable() {
    return marker;
  }
  
  @JsonProperty(JSON_PROPERTY_MARKER)
  public void setMarker_JsonNullable(JsonNullable<Integer> marker) {
    this.marker = marker;
  }

  public void setMarker(@jakarta.annotation.Nullable Integer marker) {
    this.marker = JsonNullable.<Integer>of(marker);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetChatsByChatIdMembers200Response getChatsByChatIdMembers200Response = (GetChatsByChatIdMembers200Response) o;
    return Objects.equals(this.members, getChatsByChatIdMembers200Response.members) &&
        equalsNullable(this.marker, getChatsByChatIdMembers200Response.marker);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(members, hashCodeNullable(marker));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetChatsByChatIdMembers200Response {\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    marker: ").append(toIndentedString(marker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

