/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import ru.golshansky.maxbotapi.client.model.PhotoAttachmentPayload;
import ru.golshansky.maxbotapi.client.model.VideoUrls;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetVideosByVideoToken200Response
 */
@JsonPropertyOrder({
  GetVideosByVideoToken200Response.JSON_PROPERTY_TOKEN,
  GetVideosByVideoToken200Response.JSON_PROPERTY_URLS,
  GetVideosByVideoToken200Response.JSON_PROPERTY_THUMBNAIL,
  GetVideosByVideoToken200Response.JSON_PROPERTY_WIDTH,
  GetVideosByVideoToken200Response.JSON_PROPERTY_HEIGHT,
  GetVideosByVideoToken200Response.JSON_PROPERTY_DURATION
})
@JsonTypeName("get_videos_by_videoToken_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class GetVideosByVideoToken200Response {
  public static final String JSON_PROPERTY_TOKEN = "token";
  @jakarta.annotation.Nonnull
  private String token;

  public static final String JSON_PROPERTY_URLS = "urls";
  @jakarta.annotation.Nullable
  private VideoUrls urls;

  public static final String JSON_PROPERTY_THUMBNAIL = "thumbnail";
  @jakarta.annotation.Nullable
  private PhotoAttachmentPayload thumbnail;

  public static final String JSON_PROPERTY_WIDTH = "width";
  @jakarta.annotation.Nonnull
  private Integer width;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  @jakarta.annotation.Nonnull
  private Integer height;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nonnull
  private Integer duration;

  public GetVideosByVideoToken200Response() {
  }

  public GetVideosByVideoToken200Response token(@jakarta.annotation.Nonnull String token) {
    
    this.token = token;
    return this;
  }

  /**
   * Токен видео-вложения
   * @return token
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToken() {
    return token;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToken(@jakarta.annotation.Nonnull String token) {
    this.token = token;
  }

  public GetVideosByVideoToken200Response urls(@jakarta.annotation.Nullable VideoUrls urls) {
    
    this.urls = urls;
    return this;
  }

  /**
   * Get urls
   * @return urls
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VideoUrls getUrls() {
    return urls;
  }


  @JsonProperty(JSON_PROPERTY_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrls(@jakarta.annotation.Nullable VideoUrls urls) {
    this.urls = urls;
  }

  public GetVideosByVideoToken200Response thumbnail(@jakarta.annotation.Nullable PhotoAttachmentPayload thumbnail) {
    
    this.thumbnail = thumbnail;
    return this;
  }

  /**
   * Get thumbnail
   * @return thumbnail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THUMBNAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PhotoAttachmentPayload getThumbnail() {
    return thumbnail;
  }


  @JsonProperty(JSON_PROPERTY_THUMBNAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThumbnail(@jakarta.annotation.Nullable PhotoAttachmentPayload thumbnail) {
    this.thumbnail = thumbnail;
  }

  public GetVideosByVideoToken200Response width(@jakarta.annotation.Nonnull Integer width) {
    
    this.width = width;
    return this;
  }

  /**
   * Ширина видео
   * @return width
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getWidth() {
    return width;
  }


  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWidth(@jakarta.annotation.Nonnull Integer width) {
    this.width = width;
  }

  public GetVideosByVideoToken200Response height(@jakarta.annotation.Nonnull Integer height) {
    
    this.height = height;
    return this;
  }

  /**
   * Высота видео
   * @return height
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getHeight() {
    return height;
  }


  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHeight(@jakarta.annotation.Nonnull Integer height) {
    this.height = height;
  }

  public GetVideosByVideoToken200Response duration(@jakarta.annotation.Nonnull Integer duration) {
    
    this.duration = duration;
    return this;
  }

  /**
   * Длина видео в секундах
   * @return duration
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDuration(@jakarta.annotation.Nonnull Integer duration) {
    this.duration = duration;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetVideosByVideoToken200Response getVideosByVideoToken200Response = (GetVideosByVideoToken200Response) o;
    return Objects.equals(this.token, getVideosByVideoToken200Response.token) &&
        Objects.equals(this.urls, getVideosByVideoToken200Response.urls) &&
        Objects.equals(this.thumbnail, getVideosByVideoToken200Response.thumbnail) &&
        Objects.equals(this.width, getVideosByVideoToken200Response.width) &&
        Objects.equals(this.height, getVideosByVideoToken200Response.height) &&
        Objects.equals(this.duration, getVideosByVideoToken200Response.duration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, urls, thumbnail, width, height, duration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetVideosByVideoToken200Response {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

