/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.MessageBody;
import ru.golshansky.maxbotapi.client.model.User;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Пересланное или ответное сообщение  Источник описания: [Message](https://dev.max.ru/docs-api/objects/Message)
 */
@JsonPropertyOrder({
  LinkedMessage.JSON_PROPERTY_TYPE,
  LinkedMessage.JSON_PROPERTY_SENDER,
  LinkedMessage.JSON_PROPERTY_CHAT_ID,
  LinkedMessage.JSON_PROPERTY_MESSAGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class LinkedMessage {
  /**
   * Тип связи сообщения
   */
  public enum TypeEnum {
    FORWARD(String.valueOf("forward")),
    
    REPLY(String.valueOf("reply"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_SENDER = "sender";
  @jakarta.annotation.Nullable
  private User sender;

  public static final String JSON_PROPERTY_CHAT_ID = "chat_id";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> chatId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull
  private MessageBody message;

  public LinkedMessage() {
  }

  public LinkedMessage type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Тип связи сообщения
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public LinkedMessage sender(@jakarta.annotation.Nullable User sender) {
    
    this.sender = sender;
    return this;
  }

  /**
   * Get sender
   * @return sender
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public User getSender() {
    return sender;
  }


  @JsonProperty(JSON_PROPERTY_SENDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSender(@jakarta.annotation.Nullable User sender) {
    this.sender = sender;
  }

  public LinkedMessage chatId(@jakarta.annotation.Nullable Integer chatId) {
    this.chatId = JsonNullable.<Integer>of(chatId);
    
    return this;
  }

  /**
   * ID чата, откуда пришло связанное сообщение
   * @return chatId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getChatId() {
        return chatId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CHAT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getChatId_JsonNullable() {
    return chatId;
  }
  
  @JsonProperty(JSON_PROPERTY_CHAT_ID)
  public void setChatId_JsonNullable(JsonNullable<Integer> chatId) {
    this.chatId = chatId;
  }

  public void setChatId(@jakarta.annotation.Nullable Integer chatId) {
    this.chatId = JsonNullable.<Integer>of(chatId);
  }

  public LinkedMessage message(@jakarta.annotation.Nonnull MessageBody message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MessageBody getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull MessageBody message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkedMessage linkedMessage = (LinkedMessage) o;
    return Objects.equals(this.type, linkedMessage.type) &&
        Objects.equals(this.sender, linkedMessage.sender) &&
        equalsNullable(this.chatId, linkedMessage.chatId) &&
        Objects.equals(this.message, linkedMessage.message);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, sender, hashCodeNullable(chatId), message);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkedMessage {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    chatId: ").append(toIndentedString(chatId)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

