/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Источник описания: [Message](https://dev.max.ru/docs-api/objects/Message)
 */
@JsonPropertyOrder({
  MarkupElement.JSON_PROPERTY_TYPE,
  MarkupElement.JSON_PROPERTY_FROM,
  MarkupElement.JSON_PROPERTY_LENGTH,
  MarkupElement.JSON_PROPERTY_USER_LINK,
  MarkupElement.JSON_PROPERTY_USER_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class MarkupElement {
  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private String type;

  public static final String JSON_PROPERTY_FROM = "from";
  @jakarta.annotation.Nonnull
  private Integer from;

  public static final String JSON_PROPERTY_LENGTH = "length";
  @jakarta.annotation.Nonnull
  private Integer length;

  public static final String JSON_PROPERTY_USER_LINK = "user_link";
  @jakarta.annotation.Nullable
  private JsonNullable<String> userLink = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> userId = JsonNullable.<Integer>undefined();

  public MarkupElement() {
  }

  public MarkupElement type(@jakarta.annotation.Nonnull String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Тип элемента разметки
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull String type) {
    this.type = type;
  }

  public MarkupElement from(@jakarta.annotation.Nonnull Integer from) {
    
    this.from = from;
    return this;
  }

  /**
   * Начальная позиция
   * @return from
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFrom() {
    return from;
  }


  @JsonProperty(JSON_PROPERTY_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@jakarta.annotation.Nonnull Integer from) {
    this.from = from;
  }

  public MarkupElement length(@jakarta.annotation.Nonnull Integer length) {
    
    this.length = length;
    return this;
  }

  /**
   * Длина диапазона
   * @return length
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getLength() {
    return length;
  }


  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLength(@jakarta.annotation.Nonnull Integer length) {
    this.length = length;
  }

  public MarkupElement userLink(@jakarta.annotation.Nullable String userLink) {
    this.userLink = JsonNullable.<String>of(userLink);
    
    return this;
  }

  /**
   * Ссылка на пользователя
   * @return userLink
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getUserLink() {
        return userLink.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_USER_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUserLink_JsonNullable() {
    return userLink;
  }
  
  @JsonProperty(JSON_PROPERTY_USER_LINK)
  public void setUserLink_JsonNullable(JsonNullable<String> userLink) {
    this.userLink = userLink;
  }

  public void setUserLink(@jakarta.annotation.Nullable String userLink) {
    this.userLink = JsonNullable.<String>of(userLink);
  }

  public MarkupElement userId(@jakarta.annotation.Nullable Integer userId) {
    this.userId = JsonNullable.<Integer>of(userId);
    
    return this;
  }

  /**
   * ID пользователя
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getUserId() {
        return userId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getUserId_JsonNullable() {
    return userId;
  }
  
  @JsonProperty(JSON_PROPERTY_USER_ID)
  public void setUserId_JsonNullable(JsonNullable<Integer> userId) {
    this.userId = userId;
  }

  public void setUserId(@jakarta.annotation.Nullable Integer userId) {
    this.userId = JsonNullable.<Integer>of(userId);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarkupElement markupElement = (MarkupElement) o;
    return Objects.equals(this.type, markupElement.type) &&
        Objects.equals(this.from, markupElement.from) &&
        Objects.equals(this.length, markupElement.length) &&
        equalsNullable(this.userLink, markupElement.userLink) &&
        equalsNullable(this.userId, markupElement.userId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, from, length, hashCodeNullable(userLink), hashCodeNullable(userId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarkupElement {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    userLink: ").append(toIndentedString(userLink)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

