/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.Attachment;
import ru.golshansky.maxbotapi.client.model.MarkupElement;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Содержимое сообщения. Текст + вложения. Может быть null, если сообщение содержит только пересланное сообщение  Источник описания: [Message](https://dev.max.ru/docs-api/objects/Message)
 */
@JsonPropertyOrder({
  MessageBody.JSON_PROPERTY_MID,
  MessageBody.JSON_PROPERTY_SEQ,
  MessageBody.JSON_PROPERTY_TEXT,
  MessageBody.JSON_PROPERTY_ATTACHMENTS,
  MessageBody.JSON_PROPERTY_MARKUP
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class MessageBody {
  public static final String JSON_PROPERTY_MID = "mid";
  @jakarta.annotation.Nonnull
  private String mid;

  public static final String JSON_PROPERTY_SEQ = "seq";
  @jakarta.annotation.Nonnull
  private Integer seq;

  public static final String JSON_PROPERTY_TEXT = "text";
  @jakarta.annotation.Nullable
  private JsonNullable<String> text = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ATTACHMENTS = "attachments";
  @jakarta.annotation.Nullable
  private JsonNullable<List<Attachment>> attachments = JsonNullable.<List<Attachment>>undefined();

  public static final String JSON_PROPERTY_MARKUP = "markup";
  @jakarta.annotation.Nullable
  private JsonNullable<List<MarkupElement>> markup = JsonNullable.<List<MarkupElement>>undefined();

  public MessageBody() {
  }

  public MessageBody mid(@jakarta.annotation.Nonnull String mid) {
    
    this.mid = mid;
    return this;
  }

  /**
   * ID сообщения
   * @return mid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMid() {
    return mid;
  }


  @JsonProperty(JSON_PROPERTY_MID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMid(@jakarta.annotation.Nonnull String mid) {
    this.mid = mid;
  }

  public MessageBody seq(@jakarta.annotation.Nonnull Integer seq) {
    
    this.seq = seq;
    return this;
  }

  /**
   * Порядковый номер сообщения
   * @return seq
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEQ)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSeq() {
    return seq;
  }


  @JsonProperty(JSON_PROPERTY_SEQ)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeq(@jakarta.annotation.Nonnull Integer seq) {
    this.seq = seq;
  }

  public MessageBody text(@jakarta.annotation.Nullable String text) {
    this.text = JsonNullable.<String>of(text);
    
    return this;
  }

  /**
   * Текст сообщения
   * @return text
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getText() {
        return text.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getText_JsonNullable() {
    return text;
  }
  
  @JsonProperty(JSON_PROPERTY_TEXT)
  public void setText_JsonNullable(JsonNullable<String> text) {
    this.text = text;
  }

  public void setText(@jakarta.annotation.Nullable String text) {
    this.text = JsonNullable.<String>of(text);
  }

  public MessageBody attachments(@jakarta.annotation.Nullable List<Attachment> attachments) {
    this.attachments = JsonNullable.<List<Attachment>>of(attachments);
    
    return this;
  }

  public MessageBody addAttachmentsItem(Attachment attachmentsItem) {
    if (this.attachments == null || !this.attachments.isPresent()) {
      this.attachments = JsonNullable.<List<Attachment>>of(new ArrayList<>());
    }
    try {
      this.attachments.get().add(attachmentsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Вложения сообщения. Могут быть одним из типов Attachment
   * @return attachments
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<Attachment> getAttachments() {
        return attachments.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ATTACHMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Attachment>> getAttachments_JsonNullable() {
    return attachments;
  }
  
  @JsonProperty(JSON_PROPERTY_ATTACHMENTS)
  public void setAttachments_JsonNullable(JsonNullable<List<Attachment>> attachments) {
    this.attachments = attachments;
  }

  public void setAttachments(@jakarta.annotation.Nullable List<Attachment> attachments) {
    this.attachments = JsonNullable.<List<Attachment>>of(attachments);
  }

  public MessageBody markup(@jakarta.annotation.Nullable List<MarkupElement> markup) {
    this.markup = JsonNullable.<List<MarkupElement>>of(markup);
    
    return this;
  }

  public MessageBody addMarkupItem(MarkupElement markupItem) {
    if (this.markup == null || !this.markup.isPresent()) {
      this.markup = JsonNullable.<List<MarkupElement>>of(new ArrayList<>());
    }
    try {
      this.markup.get().add(markupItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Разметка текста сообщения
   * @return markup
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<MarkupElement> getMarkup() {
        return markup.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MARKUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<MarkupElement>> getMarkup_JsonNullable() {
    return markup;
  }
  
  @JsonProperty(JSON_PROPERTY_MARKUP)
  public void setMarkup_JsonNullable(JsonNullable<List<MarkupElement>> markup) {
    this.markup = markup;
  }

  public void setMarkup(@jakarta.annotation.Nullable List<MarkupElement> markup) {
    this.markup = JsonNullable.<List<MarkupElement>>of(markup);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageBody messageBody = (MessageBody) o;
    return Objects.equals(this.mid, messageBody.mid) &&
        Objects.equals(this.seq, messageBody.seq) &&
        equalsNullable(this.text, messageBody.text) &&
        equalsNullable(this.attachments, messageBody.attachments) &&
        equalsNullable(this.markup, messageBody.markup);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(mid, seq, hashCodeNullable(text), hashCodeNullable(attachments), hashCodeNullable(markup));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageBody {\n");
    sb.append("    mid: ").append(toIndentedString(mid)).append("\n");
    sb.append("    seq: ").append(toIndentedString(seq)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    markup: ").append(toIndentedString(markup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

