/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.LinkedMessage;
import ru.golshansky.maxbotapi.client.model.MessageBody;
import ru.golshansky.maxbotapi.client.model.MessageStat;
import ru.golshansky.maxbotapi.client.model.Recipient;
import ru.golshansky.maxbotapi.client.model.User;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Сообщение в чате  Источник описания: [Message](https://dev.max.ru/docs-api/objects/Message)
 */
@JsonPropertyOrder({
  Message.JSON_PROPERTY_SENDER,
  Message.JSON_PROPERTY_RECIPIENT,
  Message.JSON_PROPERTY_TIMESTAMP,
  Message.JSON_PROPERTY_LINK,
  Message.JSON_PROPERTY_BODY,
  Message.JSON_PROPERTY_STAT,
  Message.JSON_PROPERTY_URL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class Message {
  public static final String JSON_PROPERTY_SENDER = "sender";
  @jakarta.annotation.Nullable
  private User sender;

  public static final String JSON_PROPERTY_RECIPIENT = "recipient";
  @jakarta.annotation.Nonnull
  private Recipient recipient;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @jakarta.annotation.Nonnull
  private Integer timestamp;

  public static final String JSON_PROPERTY_LINK = "link";
  @jakarta.annotation.Nullable
  private LinkedMessage link;

  public static final String JSON_PROPERTY_BODY = "body";
  @jakarta.annotation.Nonnull
  private MessageBody body;

  public static final String JSON_PROPERTY_STAT = "stat";
  @jakarta.annotation.Nullable
  private MessageStat stat;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private JsonNullable<String> url = JsonNullable.<String>undefined();

  public Message() {
  }

  public Message sender(@jakarta.annotation.Nullable User sender) {
    
    this.sender = sender;
    return this;
  }

  /**
   * Get sender
   * @return sender
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public User getSender() {
    return sender;
  }


  @JsonProperty(JSON_PROPERTY_SENDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSender(@jakarta.annotation.Nullable User sender) {
    this.sender = sender;
  }

  public Message recipient(@jakarta.annotation.Nonnull Recipient recipient) {
    
    this.recipient = recipient;
    return this;
  }

  /**
   * Get recipient
   * @return recipient
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RECIPIENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Recipient getRecipient() {
    return recipient;
  }


  @JsonProperty(JSON_PROPERTY_RECIPIENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipient(@jakarta.annotation.Nonnull Recipient recipient) {
    this.recipient = recipient;
  }

  public Message timestamp(@jakarta.annotation.Nonnull Integer timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Время создания сообщения в формате Unix-time
   * @return timestamp
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(@jakarta.annotation.Nonnull Integer timestamp) {
    this.timestamp = timestamp;
  }

  public Message link(@jakarta.annotation.Nullable LinkedMessage link) {
    
    this.link = link;
    return this;
  }

  /**
   * Get link
   * @return link
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LinkedMessage getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(@jakarta.annotation.Nullable LinkedMessage link) {
    this.link = link;
  }

  public Message body(@jakarta.annotation.Nonnull MessageBody body) {
    
    this.body = body;
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BODY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MessageBody getBody() {
    return body;
  }


  @JsonProperty(JSON_PROPERTY_BODY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBody(@jakarta.annotation.Nonnull MessageBody body) {
    this.body = body;
  }

  public Message stat(@jakarta.annotation.Nullable MessageStat stat) {
    
    this.stat = stat;
    return this;
  }

  /**
   * Get stat
   * @return stat
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MessageStat getStat() {
    return stat;
  }


  @JsonProperty(JSON_PROPERTY_STAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStat(@jakarta.annotation.Nullable MessageStat stat) {
    this.stat = stat;
  }

  public Message url(@jakarta.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
    
    return this;
  }

  /**
   * Публичная ссылка на пост в канале. Отсутствует для диалогов и групповых чатов
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getUrl() {
        return url.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUrl_JsonNullable() {
    return url;
  }
  
  @JsonProperty(JSON_PROPERTY_URL)
  public void setUrl_JsonNullable(JsonNullable<String> url) {
    this.url = url;
  }

  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.sender, message.sender) &&
        Objects.equals(this.recipient, message.recipient) &&
        Objects.equals(this.timestamp, message.timestamp) &&
        Objects.equals(this.link, message.link) &&
        Objects.equals(this.body, message.body) &&
        Objects.equals(this.stat, message.stat) &&
        equalsNullable(this.url, message.url);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(sender, recipient, timestamp, link, body, stat, hashCodeNullable(url));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    recipient: ").append(toIndentedString(recipient)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    stat: ").append(toIndentedString(stat)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

