/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Статистика сообщения. Возвращается только для постов в каналах  Источник описания: [Message](https://dev.max.ru/docs-api/objects/Message)
 */
@JsonPropertyOrder({
  MessageStat.JSON_PROPERTY_VIEWS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class MessageStat {
  public static final String JSON_PROPERTY_VIEWS = "views";
  @jakarta.annotation.Nonnull
  private Integer views;

  public MessageStat() {
  }

  public MessageStat views(@jakarta.annotation.Nonnull Integer views) {
    
    this.views = views;
    return this;
  }

  /**
   * Количество просмотров сообщения
   * @return views
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VIEWS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getViews() {
    return views;
  }


  @JsonProperty(JSON_PROPERTY_VIEWS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setViews(@jakarta.annotation.Nonnull Integer views) {
    this.views = views;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageStat messageStat = (MessageStat) o;
    return Objects.equals(this.views, messageStat.views);
  }

  @Override
  public int hashCode() {
    return Objects.hash(views);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageStat {\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

