/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Ссылка на сообщение  Источник описания: [NewMessageBody](https://dev.max.ru/docs-api/objects/NewMessageBody)
 */
@JsonPropertyOrder({
  NewMessageLink.JSON_PROPERTY_TYPE,
  NewMessageLink.JSON_PROPERTY_MID,
  NewMessageLink.JSON_PROPERTY_CHAT_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class NewMessageLink {
  /**
   * Тип связи сообщения
   */
  public enum TypeEnum {
    FORWARD(String.valueOf("forward")),
    
    REPLY(String.valueOf("reply"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  public static final String JSON_PROPERTY_MID = "mid";
  @jakarta.annotation.Nullable
  private JsonNullable<String> mid = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CHAT_ID = "chat_id";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> chatId = JsonNullable.<Integer>undefined();

  public NewMessageLink() {
  }

  public NewMessageLink type(@jakarta.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Тип связи сообщения
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  public NewMessageLink mid(@jakarta.annotation.Nullable String mid) {
    this.mid = JsonNullable.<String>of(mid);
    
    return this;
  }

  /**
   * ID сообщения
   * @return mid
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getMid() {
        return mid.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getMid_JsonNullable() {
    return mid;
  }
  
  @JsonProperty(JSON_PROPERTY_MID)
  public void setMid_JsonNullable(JsonNullable<String> mid) {
    this.mid = mid;
  }

  public void setMid(@jakarta.annotation.Nullable String mid) {
    this.mid = JsonNullable.<String>of(mid);
  }

  public NewMessageLink chatId(@jakarta.annotation.Nullable Integer chatId) {
    this.chatId = JsonNullable.<Integer>of(chatId);
    
    return this;
  }

  /**
   * ID чата
   * @return chatId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getChatId() {
        return chatId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CHAT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getChatId_JsonNullable() {
    return chatId;
  }
  
  @JsonProperty(JSON_PROPERTY_CHAT_ID)
  public void setChatId_JsonNullable(JsonNullable<Integer> chatId) {
    this.chatId = chatId;
  }

  public void setChatId(@jakarta.annotation.Nullable Integer chatId) {
    this.chatId = JsonNullable.<Integer>of(chatId);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewMessageLink newMessageLink = (NewMessageLink) o;
    return Objects.equals(this.type, newMessageLink.type) &&
        equalsNullable(this.mid, newMessageLink.mid) &&
        equalsNullable(this.chatId, newMessageLink.chatId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, hashCodeNullable(mid), hashCodeNullable(chatId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewMessageLink {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    mid: ").append(toIndentedString(mid)).append("\n");
    sb.append("    chatId: ").append(toIndentedString(chatId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

