/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.AttachmentRequest;
import ru.golshansky.maxbotapi.client.model.NewMessageLink;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Источник описания: [NewMessageBody](https://dev.max.ru/docs-api/objects/NewMessageBody)
 */
@JsonPropertyOrder({
  NewMessageBody.JSON_PROPERTY_TEXT,
  NewMessageBody.JSON_PROPERTY_ATTACHMENTS,
  NewMessageBody.JSON_PROPERTY_LINK,
  NewMessageBody.JSON_PROPERTY_NOTIFY,
  NewMessageBody.JSON_PROPERTY_FORMAT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class NewMessageBody {
  public static final String JSON_PROPERTY_TEXT = "text";
  @jakarta.annotation.Nullable
  private JsonNullable<String> text = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ATTACHMENTS = "attachments";
  @jakarta.annotation.Nullable
  private JsonNullable<List<AttachmentRequest>> attachments = JsonNullable.<List<AttachmentRequest>>undefined();

  public static final String JSON_PROPERTY_LINK = "link";
  @jakarta.annotation.Nullable
  private NewMessageLink link;

  public static final String JSON_PROPERTY_NOTIFY = "notify";
  @jakarta.annotation.Nullable
  private Boolean notify = true;

  public static final String JSON_PROPERTY_FORMAT = "format";
  @jakarta.annotation.Nullable
  private JsonNullable<String> format = JsonNullable.<String>undefined();

  public NewMessageBody() {
  }

  public NewMessageBody text(@jakarta.annotation.Nullable String text) {
    this.text = JsonNullable.<String>of(text);
    
    return this;
  }

  /**
   * до 4000 символов Новый текст сообщения
   * @return text
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getText() {
        return text.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getText_JsonNullable() {
    return text;
  }
  
  @JsonProperty(JSON_PROPERTY_TEXT)
  public void setText_JsonNullable(JsonNullable<String> text) {
    this.text = text;
  }

  public void setText(@jakarta.annotation.Nullable String text) {
    this.text = JsonNullable.<String>of(text);
  }

  public NewMessageBody attachments(@jakarta.annotation.Nullable List<AttachmentRequest> attachments) {
    this.attachments = JsonNullable.<List<AttachmentRequest>>of(attachments);
    
    return this;
  }

  public NewMessageBody addAttachmentsItem(AttachmentRequest attachmentsItem) {
    if (this.attachments == null || !this.attachments.isPresent()) {
      this.attachments = JsonNullable.<List<AttachmentRequest>>of(new ArrayList<>());
    }
    try {
      this.attachments.get().add(attachmentsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Вложения сообщения. Если пусто, все вложения будут удалены
   * @return attachments
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<AttachmentRequest> getAttachments() {
        return attachments.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ATTACHMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<AttachmentRequest>> getAttachments_JsonNullable() {
    return attachments;
  }
  
  @JsonProperty(JSON_PROPERTY_ATTACHMENTS)
  public void setAttachments_JsonNullable(JsonNullable<List<AttachmentRequest>> attachments) {
    this.attachments = attachments;
  }

  public void setAttachments(@jakarta.annotation.Nullable List<AttachmentRequest> attachments) {
    this.attachments = JsonNullable.<List<AttachmentRequest>>of(attachments);
  }

  public NewMessageBody link(@jakarta.annotation.Nullable NewMessageLink link) {
    
    this.link = link;
    return this;
  }

  /**
   * Get link
   * @return link
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NewMessageLink getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(@jakarta.annotation.Nullable NewMessageLink link) {
    this.link = link;
  }

  public NewMessageBody notify(@jakarta.annotation.Nullable Boolean notify) {
    
    this.notify = notify;
    return this;
  }

  /**
   * По умолчанию:  true  Если false, участники чата не будут уведомлены (по умолчанию  true  Шаблон: &#x60;)&#x60;
   * @return notify
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOTIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNotify() {
    return notify;
  }


  @JsonProperty(JSON_PROPERTY_NOTIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotify(@jakarta.annotation.Nullable Boolean notify) {
    this.notify = notify;
  }

  public NewMessageBody format(@jakarta.annotation.Nullable String format) {
    this.format = JsonNullable.<String>of(format);
    
    return this;
  }

  /**
   * Enum:  \&quot;markdown\&quot; \&quot;html\&quot;  Если установлен, текст сообщения будет форматирован данным способом. Для подробной информации загляните в раздел  Форматирование
   * @return format
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getFormat() {
        return format.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFormat_JsonNullable() {
    return format;
  }
  
  @JsonProperty(JSON_PROPERTY_FORMAT)
  public void setFormat_JsonNullable(JsonNullable<String> format) {
    this.format = format;
  }

  public void setFormat(@jakarta.annotation.Nullable String format) {
    this.format = JsonNullable.<String>of(format);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewMessageBody newMessageBody = (NewMessageBody) o;
    return equalsNullable(this.text, newMessageBody.text) &&
        equalsNullable(this.attachments, newMessageBody.attachments) &&
        Objects.equals(this.link, newMessageBody.link) &&
        Objects.equals(this.notify, newMessageBody.notify) &&
        equalsNullable(this.format, newMessageBody.format);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(text), hashCodeNullable(attachments), link, notify, hashCodeNullable(format));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewMessageBody {\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    notify: ").append(toIndentedString(notify)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

