/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.PhotoAttachmentRequestPayload;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PatchChatsByChatIdRequest
 */
@JsonPropertyOrder({
  PatchChatsByChatIdRequest.JSON_PROPERTY_ICON,
  PatchChatsByChatIdRequest.JSON_PROPERTY_TITLE,
  PatchChatsByChatIdRequest.JSON_PROPERTY_PIN,
  PatchChatsByChatIdRequest.JSON_PROPERTY_NOTIFY
})
@JsonTypeName("patch_chats_by_chatId_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class PatchChatsByChatIdRequest {
  public static final String JSON_PROPERTY_ICON = "icon";
  @jakarta.annotation.Nullable
  private PhotoAttachmentRequestPayload icon;

  public static final String JSON_PROPERTY_TITLE = "title";
  @jakarta.annotation.Nullable
  private JsonNullable<String> title = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PIN = "pin";
  @jakarta.annotation.Nullable
  private JsonNullable<String> pin = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NOTIFY = "notify";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> notify = JsonNullable.<Boolean>of(true);

  public PatchChatsByChatIdRequest() {
  }

  public PatchChatsByChatIdRequest icon(@jakarta.annotation.Nullable PhotoAttachmentRequestPayload icon) {
    
    this.icon = icon;
    return this;
  }

  /**
   * Get icon
   * @return icon
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ICON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PhotoAttachmentRequestPayload getIcon() {
    return icon;
  }


  @JsonProperty(JSON_PROPERTY_ICON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIcon(@jakarta.annotation.Nullable PhotoAttachmentRequestPayload icon) {
    this.icon = icon;
  }

  public PatchChatsByChatIdRequest title(@jakarta.annotation.Nullable String title) {
    this.title = JsonNullable.<String>of(title);
    
    return this;
  }

  /**
   * от 1 до 200 символов
   * @return title
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getTitle() {
        return title.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTitle_JsonNullable() {
    return title;
  }
  
  @JsonProperty(JSON_PROPERTY_TITLE)
  public void setTitle_JsonNullable(JsonNullable<String> title) {
    this.title = title;
  }

  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = JsonNullable.<String>of(title);
  }

  public PatchChatsByChatIdRequest pin(@jakarta.annotation.Nullable String pin) {
    this.pin = JsonNullable.<String>of(pin);
    
    return this;
  }

  /**
   * ID сообщения для закрепления в чате. Чтобы удалить закреплённое сообщение, используйте метод unpin
   * @return pin
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getPin() {
        return pin.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPin_JsonNullable() {
    return pin;
  }
  
  @JsonProperty(JSON_PROPERTY_PIN)
  public void setPin_JsonNullable(JsonNullable<String> pin) {
    this.pin = pin;
  }

  public void setPin(@jakarta.annotation.Nullable String pin) {
    this.pin = JsonNullable.<String>of(pin);
  }

  public PatchChatsByChatIdRequest notify(@jakarta.annotation.Nullable Boolean notify) {
    this.notify = JsonNullable.<Boolean>of(notify);
    
    return this;
  }

  /**
   * По умолчанию:  true Если true, участники получат системное уведомление об изменении
   * @return notify
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getNotify() {
        return notify.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NOTIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getNotify_JsonNullable() {
    return notify;
  }
  
  @JsonProperty(JSON_PROPERTY_NOTIFY)
  public void setNotify_JsonNullable(JsonNullable<Boolean> notify) {
    this.notify = notify;
  }

  public void setNotify(@jakarta.annotation.Nullable Boolean notify) {
    this.notify = JsonNullable.<Boolean>of(notify);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchChatsByChatIdRequest patchChatsByChatIdRequest = (PatchChatsByChatIdRequest) o;
    return Objects.equals(this.icon, patchChatsByChatIdRequest.icon) &&
        equalsNullable(this.title, patchChatsByChatIdRequest.title) &&
        equalsNullable(this.pin, patchChatsByChatIdRequest.pin) &&
        equalsNullable(this.notify, patchChatsByChatIdRequest.notify);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(icon, hashCodeNullable(title), hashCodeNullable(pin), hashCodeNullable(notify));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchChatsByChatIdRequest {\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    notify: ").append(toIndentedString(notify)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

