/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostChatsByChatIdActionsRequest
 */
@JsonPropertyOrder({
  PostChatsByChatIdActionsRequest.JSON_PROPERTY_ACTION
})
@JsonTypeName("post_chats_by_chatId_actions_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class PostChatsByChatIdActionsRequest {
  public static final String JSON_PROPERTY_ACTION = "action";
  @jakarta.annotation.Nonnull
  private String action;

  public PostChatsByChatIdActionsRequest() {
  }

  public PostChatsByChatIdActionsRequest action(@jakarta.annotation.Nonnull String action) {
    
    this.action = action;
    return this;
  }

  /**
   * Enum:  \&quot;typing_on\&quot; \&quot;sending_photo\&quot; \&quot;sending_video\&quot; \&quot;sending_audio\&quot; \&quot;sending_file\&quot;  Действие, отправляемое участникам чата. Возможные значения:  \&quot;typing_on\&quot; — Бот набирает сообщение \&quot;sending_photo\&quot; — Бот отправляет фото \&quot;sending_video\&quot; — Бот отправляет видео \&quot;sending_audio\&quot; — Бот отправляет аудиофайл \&quot;sending_file\&quot; — Бот отправляет файл
   * @return action
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAction() {
    return action;
  }


  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAction(@jakarta.annotation.Nonnull String action) {
    this.action = action;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostChatsByChatIdActionsRequest postChatsByChatIdActionsRequest = (PostChatsByChatIdActionsRequest) o;
    return Objects.equals(this.action, postChatsByChatIdActionsRequest.action);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostChatsByChatIdActionsRequest {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

