/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostSubscriptionsRequest
 */
@JsonPropertyOrder({
  PostSubscriptionsRequest.JSON_PROPERTY_URL,
  PostSubscriptionsRequest.JSON_PROPERTY_UPDATE_TYPES,
  PostSubscriptionsRequest.JSON_PROPERTY_SECRET
})
@JsonTypeName("post_subscriptions_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class PostSubscriptionsRequest {
  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nonnull
  private String url;

  public static final String JSON_PROPERTY_UPDATE_TYPES = "update_types";
  @jakarta.annotation.Nullable
  private List<String> updateTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_SECRET = "secret";
  @jakarta.annotation.Nullable
  private String secret;

  public PostSubscriptionsRequest() {
  }

  public PostSubscriptionsRequest url(@jakarta.annotation.Nonnull String url) {
    
    this.url = url;
    return this;
  }

  /**
   * URL HTTPS-endpoint вашего бота. Должен начинаться с https://
   * @return url
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@jakarta.annotation.Nonnull String url) {
    this.url = url;
  }

  public PostSubscriptionsRequest updateTypes(@jakarta.annotation.Nullable List<String> updateTypes) {
    
    this.updateTypes = updateTypes;
    return this;
  }

  public PostSubscriptionsRequest addUpdateTypesItem(String updateTypesItem) {
    if (this.updateTypes == null) {
      this.updateTypes = new ArrayList<>();
    }
    this.updateTypes.add(updateTypesItem);
    return this;
  }

  /**
   * Пример:  Список типов обновлений, которые хочет получать ваш бот. Для полного списка типов см. объект Update
   * @return updateTypes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getUpdateTypes() {
    return updateTypes;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTypes(@jakarta.annotation.Nullable List<String> updateTypes) {
    this.updateTypes = updateTypes;
  }

  public PostSubscriptionsRequest secret(@jakarta.annotation.Nullable String secret) {
    
    this.secret = secret;
    return this;
  }

  /**
   * от 5 до 256 символов Cекрет, который должен быть отправлен в заголовке X-Max-Bot-Api-Secret в каждом запросе Webhook. Разрешены только символы A-Z, a-z, 0-9, и дефис. Заголовок рекомендован, чтобы запрос поступал из установленного веб-узла  Шаблон: &#x60;^[a-zA-Z0-9_-]{5,256}$&#x60;
   * @return secret
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecret() {
    return secret;
  }


  @JsonProperty(JSON_PROPERTY_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecret(@jakarta.annotation.Nullable String secret) {
    this.secret = secret;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostSubscriptionsRequest postSubscriptionsRequest = (PostSubscriptionsRequest) o;
    return Objects.equals(this.url, postSubscriptionsRequest.url) &&
        Objects.equals(this.updateTypes, postSubscriptionsRequest.updateTypes) &&
        Objects.equals(this.secret, postSubscriptionsRequest.secret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, updateTypes, secret);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostSubscriptionsRequest {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    updateTypes: ").append(toIndentedString(updateTypes)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

