/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.FailedUserDetails;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostChatsByChatIdMembers200Response
 */
@JsonPropertyOrder({
  PostChatsByChatIdMembers200Response.JSON_PROPERTY_SUCCESS,
  PostChatsByChatIdMembers200Response.JSON_PROPERTY_MESSAGE,
  PostChatsByChatIdMembers200Response.JSON_PROPERTY_FAILED_USER_IDS,
  PostChatsByChatIdMembers200Response.JSON_PROPERTY_FAILED_USER_DETAILS
})
@JsonTypeName("post_chats_by_chatId_members_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class PostChatsByChatIdMembers200Response {
  public static final String JSON_PROPERTY_SUCCESS = "success";
  @jakarta.annotation.Nonnull
  private Boolean success;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_FAILED_USER_IDS = "failed_user_ids";
  @jakarta.annotation.Nullable
  private JsonNullable<List<Integer>> failedUserIds = JsonNullable.<List<Integer>>undefined();

  public static final String JSON_PROPERTY_FAILED_USER_DETAILS = "failed_user_details";
  @jakarta.annotation.Nullable
  private JsonNullable<List<FailedUserDetails>> failedUserDetails = JsonNullable.<List<FailedUserDetails>>undefined();

  public PostChatsByChatIdMembers200Response() {
  }

  public PostChatsByChatIdMembers200Response success(@jakarta.annotation.Nonnull Boolean success) {
    
    this.success = success;
    return this;
  }

  /**
   * true, если запрос был успешным, false — в противном случае
   * @return success
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSuccess() {
    return success;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSuccess(@jakarta.annotation.Nonnull Boolean success) {
    this.success = success;
  }

  public PostChatsByChatIdMembers200Response message(@jakarta.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Объяснительное сообщение, если результат не был успешным
   * @return message
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }

  public PostChatsByChatIdMembers200Response failedUserIds(@jakarta.annotation.Nullable List<Integer> failedUserIds) {
    this.failedUserIds = JsonNullable.<List<Integer>>of(failedUserIds);
    
    return this;
  }

  public PostChatsByChatIdMembers200Response addFailedUserIdsItem(Integer failedUserIdsItem) {
    if (this.failedUserIds == null || !this.failedUserIds.isPresent()) {
      this.failedUserIds = JsonNullable.<List<Integer>>of(new ArrayList<>());
    }
    try {
      this.failedUserIds.get().add(failedUserIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * ID пользователей, которых не удалось добавить
   * @return failedUserIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<Integer> getFailedUserIds() {
        return failedUserIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FAILED_USER_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Integer>> getFailedUserIds_JsonNullable() {
    return failedUserIds;
  }
  
  @JsonProperty(JSON_PROPERTY_FAILED_USER_IDS)
  public void setFailedUserIds_JsonNullable(JsonNullable<List<Integer>> failedUserIds) {
    this.failedUserIds = failedUserIds;
  }

  public void setFailedUserIds(@jakarta.annotation.Nullable List<Integer> failedUserIds) {
    this.failedUserIds = JsonNullable.<List<Integer>>of(failedUserIds);
  }

  public PostChatsByChatIdMembers200Response failedUserDetails(@jakarta.annotation.Nullable List<FailedUserDetails> failedUserDetails) {
    this.failedUserDetails = JsonNullable.<List<FailedUserDetails>>of(failedUserDetails);
    
    return this;
  }

  public PostChatsByChatIdMembers200Response addFailedUserDetailsItem(FailedUserDetails failedUserDetailsItem) {
    if (this.failedUserDetails == null || !this.failedUserDetails.isPresent()) {
      this.failedUserDetails = JsonNullable.<List<FailedUserDetails>>of(new ArrayList<>());
    }
    try {
      this.failedUserDetails.get().add(failedUserDetailsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Подробное описание, почему пользователь не был добавлен в чат
   * @return failedUserDetails
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<FailedUserDetails> getFailedUserDetails() {
        return failedUserDetails.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FAILED_USER_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<FailedUserDetails>> getFailedUserDetails_JsonNullable() {
    return failedUserDetails;
  }
  
  @JsonProperty(JSON_PROPERTY_FAILED_USER_DETAILS)
  public void setFailedUserDetails_JsonNullable(JsonNullable<List<FailedUserDetails>> failedUserDetails) {
    this.failedUserDetails = failedUserDetails;
  }

  public void setFailedUserDetails(@jakarta.annotation.Nullable List<FailedUserDetails> failedUserDetails) {
    this.failedUserDetails = JsonNullable.<List<FailedUserDetails>>of(failedUserDetails);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostChatsByChatIdMembers200Response postChatsByChatIdMembers200Response = (PostChatsByChatIdMembers200Response) o;
    return Objects.equals(this.success, postChatsByChatIdMembers200Response.success) &&
        Objects.equals(this.message, postChatsByChatIdMembers200Response.message) &&
        equalsNullable(this.failedUserIds, postChatsByChatIdMembers200Response.failedUserIds) &&
        equalsNullable(this.failedUserDetails, postChatsByChatIdMembers200Response.failedUserDetails);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, message, hashCodeNullable(failedUserIds), hashCodeNullable(failedUserDetails));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostChatsByChatIdMembers200Response {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    failedUserIds: ").append(toIndentedString(failedUserIds)).append("\n");
    sb.append("    failedUserDetails: ").append(toIndentedString(failedUserDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

