/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.NewMessageBody;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostAnswersRequest
 */
@JsonPropertyOrder({
  PostAnswersRequest.JSON_PROPERTY_MESSAGE,
  PostAnswersRequest.JSON_PROPERTY_NOTIFICATION
})
@JsonTypeName("post_answers_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class PostAnswersRequest {
  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable
  private NewMessageBody message;

  public static final String JSON_PROPERTY_NOTIFICATION = "notification";
  @jakarta.annotation.Nullable
  private JsonNullable<String> notification = JsonNullable.<String>undefined();

  public PostAnswersRequest() {
  }

  public PostAnswersRequest message(@jakarta.annotation.Nullable NewMessageBody message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NewMessageBody getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@jakarta.annotation.Nullable NewMessageBody message) {
    this.message = message;
  }

  public PostAnswersRequest notification(@jakarta.annotation.Nullable String notification) {
    this.notification = JsonNullable.<String>of(notification);
    
    return this;
  }

  /**
   * Заполните это, если хотите просто отправить одноразовое уведомление пользователю
   * @return notification
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getNotification() {
        return notification.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NOTIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getNotification_JsonNullable() {
    return notification;
  }
  
  @JsonProperty(JSON_PROPERTY_NOTIFICATION)
  public void setNotification_JsonNullable(JsonNullable<String> notification) {
    this.notification = notification;
  }

  public void setNotification(@jakarta.annotation.Nullable String notification) {
    this.notification = JsonNullable.<String>of(notification);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostAnswersRequest postAnswersRequest = (PostAnswersRequest) o;
    return Objects.equals(this.message, postAnswersRequest.message) &&
        equalsNullable(this.notification, postAnswersRequest.notification);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, hashCodeNullable(notification));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostAnswersRequest {\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    notification: ").append(toIndentedString(notification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

