/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.ChatAdmin;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostChatsByChatIdMembersAdminsRequest
 */
@JsonPropertyOrder({
  PostChatsByChatIdMembersAdminsRequest.JSON_PROPERTY_ADMINS,
  PostChatsByChatIdMembersAdminsRequest.JSON_PROPERTY_MARKER
})
@JsonTypeName("post_chats_by_chatId_members_admins_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class PostChatsByChatIdMembersAdminsRequest {
  public static final String JSON_PROPERTY_ADMINS = "admins";
  @jakarta.annotation.Nonnull
  private List<ChatAdmin> admins = new ArrayList<>();

  public static final String JSON_PROPERTY_MARKER = "marker";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> marker = JsonNullable.<Integer>undefined();

  public PostChatsByChatIdMembersAdminsRequest() {
  }

  public PostChatsByChatIdMembersAdminsRequest admins(@jakarta.annotation.Nonnull List<ChatAdmin> admins) {
    
    this.admins = admins;
    return this;
  }

  public PostChatsByChatIdMembersAdminsRequest addAdminsItem(ChatAdmin adminsItem) {
    if (this.admins == null) {
      this.admins = new ArrayList<>();
    }
    this.admins.add(adminsItem);
    return this;
  }

  /**
   * Список пользователей, которые получат права администратора чата
   * @return admins
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADMINS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ChatAdmin> getAdmins() {
    return admins;
  }


  @JsonProperty(JSON_PROPERTY_ADMINS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdmins(@jakarta.annotation.Nonnull List<ChatAdmin> admins) {
    this.admins = admins;
  }

  public PostChatsByChatIdMembersAdminsRequest marker(@jakarta.annotation.Nullable Integer marker) {
    this.marker = JsonNullable.<Integer>of(marker);
    
    return this;
  }

  /**
   * Указатель на следующую страницу данных
   * @return marker
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getMarker() {
        return marker.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MARKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getMarker_JsonNullable() {
    return marker;
  }
  
  @JsonProperty(JSON_PROPERTY_MARKER)
  public void setMarker_JsonNullable(JsonNullable<Integer> marker) {
    this.marker = marker;
  }

  public void setMarker(@jakarta.annotation.Nullable Integer marker) {
    this.marker = JsonNullable.<Integer>of(marker);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostChatsByChatIdMembersAdminsRequest postChatsByChatIdMembersAdminsRequest = (PostChatsByChatIdMembersAdminsRequest) o;
    return Objects.equals(this.admins, postChatsByChatIdMembersAdminsRequest.admins) &&
        equalsNullable(this.marker, postChatsByChatIdMembersAdminsRequest.marker);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(admins, hashCodeNullable(marker));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostChatsByChatIdMembersAdminsRequest {\n");
    sb.append("    admins: ").append(toIndentedString(admins)).append("\n");
    sb.append("    marker: ").append(toIndentedString(marker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

