/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PutChatsByChatIdPinRequest
 */
@JsonPropertyOrder({
  PutChatsByChatIdPinRequest.JSON_PROPERTY_MESSAGE_ID,
  PutChatsByChatIdPinRequest.JSON_PROPERTY_NOTIFY
})
@JsonTypeName("put_chats_by_chatId_pin_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class PutChatsByChatIdPinRequest {
  public static final String JSON_PROPERTY_MESSAGE_ID = "message_id";
  @jakarta.annotation.Nonnull
  private String messageId;

  public static final String JSON_PROPERTY_NOTIFY = "notify";
  @jakarta.annotation.Nullable
  private JsonNullable<Boolean> notify = JsonNullable.<Boolean>of(true);

  public PutChatsByChatIdPinRequest() {
  }

  public PutChatsByChatIdPinRequest messageId(@jakarta.annotation.Nonnull String messageId) {
    
    this.messageId = messageId;
    return this;
  }

  /**
   * ID сообщения, которое нужно закрепить. Соответствует полю Message.body.mid
   * @return messageId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MESSAGE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessageId() {
    return messageId;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageId(@jakarta.annotation.Nonnull String messageId) {
    this.messageId = messageId;
  }

  public PutChatsByChatIdPinRequest notify(@jakarta.annotation.Nullable Boolean notify) {
    this.notify = JsonNullable.<Boolean>of(notify);
    
    return this;
  }

  /**
   * По умолчанию:  true Если true, участники получат уведомление с системным сообщением о закреплении
   * @return notify
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getNotify() {
        return notify.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NOTIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getNotify_JsonNullable() {
    return notify;
  }
  
  @JsonProperty(JSON_PROPERTY_NOTIFY)
  public void setNotify_JsonNullable(JsonNullable<Boolean> notify) {
    this.notify = notify;
  }

  public void setNotify(@jakarta.annotation.Nullable Boolean notify) {
    this.notify = JsonNullable.<Boolean>of(notify);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutChatsByChatIdPinRequest putChatsByChatIdPinRequest = (PutChatsByChatIdPinRequest) o;
    return Objects.equals(this.messageId, putChatsByChatIdPinRequest.messageId) &&
        equalsNullable(this.notify, putChatsByChatIdPinRequest.notify);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageId, hashCodeNullable(notify));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutChatsByChatIdPinRequest {\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    notify: ").append(toIndentedString(notify)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

