/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Получатель сообщения. Может быть пользователем или чатом  Источник описания: [Message](https://dev.max.ru/docs-api/objects/Message)
 */
@JsonPropertyOrder({
  Recipient.JSON_PROPERTY_CHAT_ID,
  Recipient.JSON_PROPERTY_CHAT_TYPE,
  Recipient.JSON_PROPERTY_USER_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class Recipient {
  public static final String JSON_PROPERTY_CHAT_ID = "chat_id";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> chatId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_CHAT_TYPE = "chat_type";
  @jakarta.annotation.Nonnull
  private String chatType;

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> userId = JsonNullable.<Integer>undefined();

  public Recipient() {
  }

  public Recipient chatId(@jakarta.annotation.Nullable Integer chatId) {
    this.chatId = JsonNullable.<Integer>of(chatId);
    
    return this;
  }

  /**
   * ID чата
   * @return chatId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getChatId() {
        return chatId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CHAT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getChatId_JsonNullable() {
    return chatId;
  }
  
  @JsonProperty(JSON_PROPERTY_CHAT_ID)
  public void setChatId_JsonNullable(JsonNullable<Integer> chatId) {
    this.chatId = chatId;
  }

  public void setChatId(@jakarta.annotation.Nullable Integer chatId) {
    this.chatId = JsonNullable.<Integer>of(chatId);
  }

  public Recipient chatType(@jakarta.annotation.Nonnull String chatType) {
    
    this.chatType = chatType;
    return this;
  }

  /**
   * Тип чата получателя
   * @return chatType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHAT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getChatType() {
    return chatType;
  }


  @JsonProperty(JSON_PROPERTY_CHAT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChatType(@jakarta.annotation.Nonnull String chatType) {
    this.chatType = chatType;
  }

  public Recipient userId(@jakarta.annotation.Nullable Integer userId) {
    this.userId = JsonNullable.<Integer>of(userId);
    
    return this;
  }

  /**
   * ID пользователя-получателя
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getUserId() {
        return userId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getUserId_JsonNullable() {
    return userId;
  }
  
  @JsonProperty(JSON_PROPERTY_USER_ID)
  public void setUserId_JsonNullable(JsonNullable<Integer> userId) {
    this.userId = userId;
  }

  public void setUserId(@jakarta.annotation.Nullable Integer userId) {
    this.userId = JsonNullable.<Integer>of(userId);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Recipient recipient = (Recipient) o;
    return equalsNullable(this.chatId, recipient.chatId) &&
        Objects.equals(this.chatType, recipient.chatType) &&
        equalsNullable(this.userId, recipient.userId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(chatId), chatType, hashCodeNullable(userId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recipient {\n");
    sb.append("    chatId: ").append(toIndentedString(chatId)).append("\n");
    sb.append("    chatType: ").append(toIndentedString(chatType)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

