/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Источник описания: [GET /subscriptions](https://dev.max.ru/docs-api/methods/GET/subscriptions)
 */
@JsonPropertyOrder({
  Subscription.JSON_PROPERTY_URL,
  Subscription.JSON_PROPERTY_UPDATE_TYPES,
  Subscription.JSON_PROPERTY_SECRET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class Subscription {
  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nonnull
  private String url;

  public static final String JSON_PROPERTY_UPDATE_TYPES = "update_types";
  @jakarta.annotation.Nullable
  private JsonNullable<List<String>> updateTypes = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_SECRET = "secret";
  @jakarta.annotation.Nullable
  private JsonNullable<String> secret = JsonNullable.<String>undefined();

  public Subscription() {
  }

  public Subscription url(@jakarta.annotation.Nonnull String url) {
    
    this.url = url;
    return this;
  }

  /**
   * Webhook URL
   * @return url
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@jakarta.annotation.Nonnull String url) {
    this.url = url;
  }

  public Subscription updateTypes(@jakarta.annotation.Nullable List<String> updateTypes) {
    this.updateTypes = JsonNullable.<List<String>>of(updateTypes);
    
    return this;
  }

  public Subscription addUpdateTypesItem(String updateTypesItem) {
    if (this.updateTypes == null || !this.updateTypes.isPresent()) {
      this.updateTypes = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.updateTypes.get().add(updateTypesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Типы обновлений
   * @return updateTypes
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<String> getUpdateTypes() {
        return updateTypes.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_UPDATE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getUpdateTypes_JsonNullable() {
    return updateTypes;
  }
  
  @JsonProperty(JSON_PROPERTY_UPDATE_TYPES)
  public void setUpdateTypes_JsonNullable(JsonNullable<List<String>> updateTypes) {
    this.updateTypes = updateTypes;
  }

  public void setUpdateTypes(@jakarta.annotation.Nullable List<String> updateTypes) {
    this.updateTypes = JsonNullable.<List<String>>of(updateTypes);
  }

  public Subscription secret(@jakarta.annotation.Nullable String secret) {
    this.secret = JsonNullable.<String>of(secret);
    
    return this;
  }

  /**
   * Секрет Webhook
   * @return secret
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getSecret() {
        return secret.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSecret_JsonNullable() {
    return secret;
  }
  
  @JsonProperty(JSON_PROPERTY_SECRET)
  public void setSecret_JsonNullable(JsonNullable<String> secret) {
    this.secret = secret;
  }

  public void setSecret(@jakarta.annotation.Nullable String secret) {
    this.secret = JsonNullable.<String>of(secret);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Subscription subscription = (Subscription) o;
    return Objects.equals(this.url, subscription.url) &&
        equalsNullable(this.updateTypes, subscription.updateTypes) &&
        equalsNullable(this.secret, subscription.secret);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, hashCodeNullable(updateTypes), hashCodeNullable(secret));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Subscription {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    updateTypes: ").append(toIndentedString(updateTypes)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

