/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.golshansky.maxbotapi.client.model.Message;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Объект Update представляет различные типы событий, произошедших в чате. См. его наследников Чтобы получать события из группового чата или канала, назначьте бота администратором  Источник описания: [Update](https://dev.max.ru/docs-api/objects/Update)
 */
@JsonPropertyOrder({
  Update.JSON_PROPERTY_UPDATE_TYPE,
  Update.JSON_PROPERTY_TIMESTAMP,
  Update.JSON_PROPERTY_MESSAGE,
  Update.JSON_PROPERTY_USER_LOCALE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class Update {
  public static final String JSON_PROPERTY_UPDATE_TYPE = "update_type";
  @jakarta.annotation.Nonnull
  private String updateType;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @jakarta.annotation.Nonnull
  private Integer timestamp;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull
  private Message message;

  public static final String JSON_PROPERTY_USER_LOCALE = "user_locale";
  @jakarta.annotation.Nullable
  private JsonNullable<String> userLocale = JsonNullable.<String>undefined();

  public Update() {
  }

  public Update updateType(@jakarta.annotation.Nonnull String updateType) {
    
    this.updateType = updateType;
    return this;
  }

  /**
   * message_created
   * @return updateType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UPDATE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUpdateType() {
    return updateType;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdateType(@jakarta.annotation.Nonnull String updateType) {
    this.updateType = updateType;
  }

  public Update timestamp(@jakarta.annotation.Nonnull Integer timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Unix-время, когда произошло событие
   * @return timestamp
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(@jakarta.annotation.Nonnull Integer timestamp) {
    this.timestamp = timestamp;
  }

  public Update message(@jakarta.annotation.Nonnull Message message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Message getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull Message message) {
    this.message = message;
  }

  public Update userLocale(@jakarta.annotation.Nullable String userLocale) {
    this.userLocale = JsonNullable.<String>of(userLocale);
    
    return this;
  }

  /**
   * Текущий язык пользователя в формате IETF BCP 47. Доступно только в диалогах
   * @return userLocale
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getUserLocale() {
        return userLocale.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_USER_LOCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUserLocale_JsonNullable() {
    return userLocale;
  }
  
  @JsonProperty(JSON_PROPERTY_USER_LOCALE)
  public void setUserLocale_JsonNullable(JsonNullable<String> userLocale) {
    this.userLocale = userLocale;
  }

  public void setUserLocale(@jakarta.annotation.Nullable String userLocale) {
    this.userLocale = JsonNullable.<String>of(userLocale);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Update update = (Update) o;
    return Objects.equals(this.updateType, update.updateType) &&
        Objects.equals(this.timestamp, update.timestamp) &&
        Objects.equals(this.message, update.message) &&
        equalsNullable(this.userLocale, update.userLocale);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(updateType, timestamp, message, hashCodeNullable(userLocale));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Update {\n");
    sb.append("    updateType: ").append(toIndentedString(updateType)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    userLocale: ").append(toIndentedString(userLocale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

