/*
 * Методы API MAX
 * Сгенерировано 14:39:04 21.04.2026 на основе официальной документации [API MAX](https://dev.max.ru/docs-api)
 *
 * The version of the OpenAPI document: generated
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.golshansky.maxbotapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * URL-ы для скачивания или воспроизведения видео. Может быть null, если видео недоступно  Источник описания: [GET /videos/{videoToken}](https://dev.max.ru/docs-api/methods/GET/videos/-videoToken-)
 */
@JsonPropertyOrder({
  VideoUrls.JSON_PROPERTY_MP4,
  VideoUrls.JSON_PROPERTY_HLS,
  VideoUrls.JSON_PROPERTY_DOWNLOAD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class VideoUrls {
  public static final String JSON_PROPERTY_MP4 = "mp4";
  @jakarta.annotation.Nullable
  private JsonNullable<String> mp4 = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_HLS = "hls";
  @jakarta.annotation.Nullable
  private JsonNullable<String> hls = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DOWNLOAD = "download";
  @jakarta.annotation.Nullable
  private JsonNullable<String> download = JsonNullable.<String>undefined();

  public VideoUrls() {
  }

  public VideoUrls mp4(@jakarta.annotation.Nullable String mp4) {
    this.mp4 = JsonNullable.<String>of(mp4);
    
    return this;
  }

  /**
   * Ссылка на MP4
   * @return mp4
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getMp4() {
        return mp4.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MP4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getMp4_JsonNullable() {
    return mp4;
  }
  
  @JsonProperty(JSON_PROPERTY_MP4)
  public void setMp4_JsonNullable(JsonNullable<String> mp4) {
    this.mp4 = mp4;
  }

  public void setMp4(@jakarta.annotation.Nullable String mp4) {
    this.mp4 = JsonNullable.<String>of(mp4);
  }

  public VideoUrls hls(@jakarta.annotation.Nullable String hls) {
    this.hls = JsonNullable.<String>of(hls);
    
    return this;
  }

  /**
   * Ссылка на HLS
   * @return hls
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getHls() {
        return hls.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getHls_JsonNullable() {
    return hls;
  }
  
  @JsonProperty(JSON_PROPERTY_HLS)
  public void setHls_JsonNullable(JsonNullable<String> hls) {
    this.hls = hls;
  }

  public void setHls(@jakarta.annotation.Nullable String hls) {
    this.hls = JsonNullable.<String>of(hls);
  }

  public VideoUrls download(@jakarta.annotation.Nullable String download) {
    this.download = JsonNullable.<String>of(download);
    
    return this;
  }

  /**
   * Ссылка на скачивание
   * @return download
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDownload() {
        return download.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DOWNLOAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDownload_JsonNullable() {
    return download;
  }
  
  @JsonProperty(JSON_PROPERTY_DOWNLOAD)
  public void setDownload_JsonNullable(JsonNullable<String> download) {
    this.download = download;
  }

  public void setDownload(@jakarta.annotation.Nullable String download) {
    this.download = JsonNullable.<String>of(download);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoUrls videoUrls = (VideoUrls) o;
    return equalsNullable(this.mp4, videoUrls.mp4) &&
        equalsNullable(this.hls, videoUrls.hls) &&
        equalsNullable(this.download, videoUrls.download);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(mp4), hashCodeNullable(hls), hashCodeNullable(download));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoUrls {\n");
    sb.append("    mp4: ").append(toIndentedString(mp4)).append("\n");
    sb.append("    hls: ").append(toIndentedString(hls)).append("\n");
    sb.append("    download: ").append(toIndentedString(download)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

